import React from 'react';
import { ActionList, ActionListGroup, ActionListItem } from './index';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

// default original
// figma.connect(
//   ActionList,
//   'https://www.figma.com/design/YqvMyyV4G347jSOgfYXi29/test-code-connect?node-id=6780-15839&m=dev',
//   {
//     props: {
//       withOptionalSteps: figma.boolean('With optional steps'),
//       type: figma.enum('Type', {
//         'Single group': 'single-group',
//         'Single w Kebab': 'single-w-kebab',
//         'Action icons only': 'action-icons-only',
//         'Wizard (Default)': 'wizard--default-',
//         'modal form list': 'modal-form-list',
//         'Multiple groups': 'multiple-groups'
//       })
//     },
//     example: (props) => <ActionList />
//   }
// );

figma.connect(
  ActionList,
  'https://www.figma.com/design/YqvMyyV4G347jSOgfYXi29/test-code-connect?node-id=6780-15839&m=dev',
  {
    // variant: { Type: 'Single group' },
    props: {
      children: figma.children('*')
    },
    example: ({ children }) => (
      <ActionList>
        {/* Example code, note each button should be wrapped
          in an ActionListItem and groups of ActionListItems
          should be contained in separate ActionListGroup */}
        <ActionListGroup>
          <ActionListItem>{children}</ActionListItem>
        </ActionListGroup>
      </ActionList>
    )
  }
);
