import React from 'react';
import { Button } from './Button';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Button, 'https://www.figma.com/design/YqvMyyV4G347jSOgfYXi29/test-code-connect?node-id=1259-678&m=dev', {
  props: {
    variant: figma.enum('Type', {
      Primary: 'primary',
      Secondary: 'secondary',
      'Secondary Danger': 'secondary',
      'Secondary Progress': 'secondary',
      Tertiary: 'tertiary',
      Danger: 'danger',
      Warning: 'warning'
    }),
    size: figma.enum('Size', {
      Default: undefined,
      Small: 'sm'
    }),
    isDanger: figma.enum('Type', {
      'Secondary Danger': true
    }),
    isDisabled: figma.enum('State', {
      Disabled: true
    }),
    iconPosition: figma.boolean('Icon right', {
      true: 'end',
      false: undefined
    }),
    icon: figma.children(['IconWrapper', 'Icon']),
    text: figma.string('✏️ Text'),
    isLoading: figma.enum('Type', {
      Progress: true,
      'Secondary Progress': true
    }),
    spinnerAriaValueText: figma.enum('Type', {
      Progress: 'Loading',
      'Secondary Progress': 'Loading'
    }),
    spinnerAriaLabel: figma.enum('Type', {
      Progress: 'Content being loaded',
      'Secondary Progress': 'Content being loaded'
    })
  },
  example: ({ text, ...props }) => <Button {...props}>{text}</Button>
});
