// import figma from "@figma/code-connect"
// import { CardActions } from "./CardActions"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   CardActions,
//   "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=3144-17097&m=dev",
//   {
//     props: {
//       expandableToggleAtEnd: figma.boolean("Expandable toggle at end"),
//       actionSwap: figma.instance("Action swap"),
//       selectable: figma.boolean("Selectable"),
//       headerAction: figma.boolean("Header action"),
//     },
//     example: (props) => <CardActions />,
//   },
// )
