// import figma from '@figma/code-connect';
// import { ClickableActionableCard } from './ClickableActionableCard';

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   ClickableActionableCard,
//   'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=3144-18665&m=dev',
//   {
//     props: {
//       cardHeader: figma.boolean('Card header'),
//       cardFooter: figma.boolean('Card footer'),
//       cardTitle: figma.string('Card title'),
//       cardBody: figma.boolean('Card body'),
//       headerAction: figma.boolean('Header action'),
//       headerImage: figma.boolean('Header image'),
//       cardDescription: figma.boolean('Card description'),
//       titleIconAtStart: figma.boolean('Title icon at start'),
//       footer: figma.string('Footer'),
//       bodyText: figma.boolean('Body text'),
//       text: figma.string('Text'),
//       titleIconAtEnd: figma.boolean('Title icon at end'),
//       description: figma.string('Description'),
//       bodyComponentSlots: figma.boolean('Body component slots'),
//       expandableBody: figma.boolean('Expandable body'),
//       footerComponentSlots: figma.boolean('Footer component slots')
//     },
//     example: (props) => <ClickableActionableCard />
//   }
// );
