// import React from "react"
// import { SingleSelectCard } from "./SingleSelectCard"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   SingleSelectCard,
//   "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=27155-32360&m=dev",
//   {
//     props: {
//       cardFooter: figma.boolean("Card footer"),
//       headerImage: figma.boolean("Header image"),
//       cardHeader: figma.boolean("Card header"),
//       cardTitle: figma.string("Card title"),
//       text: figma.string("Text"),
//       footer: figma.string("Footer"),
//       cardDescription: figma.boolean("Card description"),
//       description: figma.string("Description"),
//       titleIconAtStart: figma.boolean("Title icon at start"),
//       titleIconAtEnd: figma.boolean("Title icon at end"),
//       bodyComponentSlots: figma.boolean("Body component slots"),
//       cardBody: figma.boolean("Card body"),
//       bodyText: figma.boolean("Body text"),
//       expandableBody: figma.boolean("Expandable body"),
//       footerComponentSlots: figma.boolean("Footer component slots"),
//     },
//     example: (props) => <SingleSelectCard />,
//   },
// )
