// import figma from '@figma/code-connect';
// import { Card } from './Card';

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   Card,
//   'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=24156-227236&m=dev',
//   {
//     props: {},
//     example: (props) => (
//       <Card id="utilization-card-1-card" component="div">
//         <CardTitle>
//           <Title headingLevel="h4" size="lg">
//             Top Utilized Clusters
//           </Title>
//         </CardTitle>
//       </Card>
//     )
//   }
// );
