import React from 'react';
import { Checkbox } from './Checkbox';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/YqvMyyV4G347jSOgfYXi29/test-code-connect?node-id=157-3078&m=dev',
  {
    props: {
      description: figma.boolean('Description', {
        true: figma.string('✏️ Description'),
        false: undefined
      }),
      label: figma.enum('Type', {
        'With Label': figma.string('✏️ Toggle label')
      }),
      isDisabled: figma.enum('State', {
        Disabled: true
      }),
      labelPosition: figma.enum('Label placement', {
        Reversed: 'start'
      })
    },
    example: (props) => <Checkbox id="checkbox-id" {...props} />
  }
);
