demo_app:
  runs-on: ubuntu-latest
  env:
    GH_PR_NUM: ${{ github.event.number }}
  needs: build
  steps:
    %checkout%
    %install%
    %dist%
    - name: Build demo app
      run: yarn build:integration
    - name: Upload demo app
      uses: actions/upload-artifact@v2
      with:
        name: demo-app
        path: packages/react-integration/demo-app-ts/public
