- uses: actions/setup-node@v1
  with:
    node-version: '18'
- uses: actions/cache@v2
  id: yarn-cache
  name: Cache npm deps
  with:
    path: |
     node_modules
     **/node_modules
     ~/.cache/Cypress
    key: ${{ runner.os }}-yarn-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
- run: yarn install --frozen-lockfile
  if: steps.yarn-cache.outputs.cache-hit != 'true'

