lint:
  runs-on: ubuntu-latest
  env:
    GH_PR_NUM: ${{ github.event.number }}
  needs: build
  steps:
    %checkout%
    %install%
    - uses: actions/cache@v2
      id: lint-cache
      name: Load lint cache
      with:
        path: '.eslintcache'
        key: ${{ runner.os }}-lint-14-${{ secrets.CACHE_VERSION }}-${{ hashFiles('yarn.lock') }}
    - name: ESLint
      run: yarn lint:ts
    - name: MDLint
      run: yarn lint:md
    - name: '@patternfly/patternfly versions match'
      run: yarn lint:versions

