test_integration:
  runs-on: ubuntu-latest
  needs: demo_app
  strategy:
    fail-fast: false
    matrix:
      worker_num: [0, 1, 2, 3, 4]
      worker_count: [5]
  steps:
    %checkout%
    %install%
    %dist%
    - name: Download demo app
      uses: actions/download-artifact@v2
      with:
        name: demo-app
        path: packages/react-integration/demo-app-ts/public
    - run: printenv
    - name: Cypress tests
      run: yarn serve:integration & yarn test:integration -s $(node .github/split.js)
      env:
        WORKER_NUM: ${{ matrix.worker_num }}
        WORKER_COUNT: ${{ matrix.worker_count }}
