version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Should pickup monorepo in root
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    allow:
      # Just bump core for now
      - dependency-name: "@patternfly/patternfly"
    labels:
      - "infrastructure"
