git push --delete upstream @patternfly/react-catalog-view-extension@4.13.22
git push --delete upstream @patternfly/react-charts@6.15.34
git push --delete upstream @patternfly/react-code-editor@4.3.89
git push --delete upstream @patternfly/react-console@4.14.0
git push --delete upstream @patternfly/react-core@4.163.0
git push --delete upstream @patternfly/react-docs@5.23.18
git push --delete upstream @patternfly/react-icons@4.13.2
git push --delete upstream @patternfly/react-inline-edit-extension@4.7.114
git push --delete upstream demo-app-ts@4.123.0
git push --delete upstream @patternfly/react-integration@4.125.0
git push --delete upstream @patternfly/react-log-viewer@4.7.27
git push --delete upstream @patternfly/react-styles@4.12.6
git push --delete upstream @patternfly/react-table@4.31.13
git push --delete upstream @patternfly/react-tokens@4.14.3
git push --delete upstream @patternfly/react-styles@4.12.6
git push --delete upstream @patternfly/react-table@4.31.13
git push --delete upstream @patternfly/react-tokens@4.14.3
git push --delete upstream @patternfly/react-topology@4.9.108
git push --delete upstream @patternfly/react-virtualized-extension@4.9.78
