export const BASE_URL = {
  PATTERNFLY_ORG: 'http://www.patternfly.org/pattern-library/',
  REACT_BOOTSTRAP: 'https://react-bootstrap.github.io/'
};

export const DOCUMENTATION_URL = {
  PATTERNFLY_ORG_COMMUNICATION: BASE_URL.PATTERNFLY_ORG + 'communication/',
  PATTERNFLY_ORG_WIDGETS: BASE_URL.PATTERNFLY_ORG + 'widgets/',
  PATTERNFLY_ORG_NAVIGATION: BASE_URL.PATTERNFLY_ORG + 'navigation/',
  PATTERNFLY_ORG_CARDS: BASE_URL.PATTERNFLY_ORG + 'cards/',
  PATTERNFLY_ORG_DATA_VISUALIZATION:
    BASE_URL.PATTERNFLY_ORG + 'data-visualization/',
  PATTERNFLY_ORG_FORMS: BASE_URL.PATTERNFLY_ORG + 'forms-and-controls/',
  PATTERNFLY_ORG_CONTENT_VIEWS: BASE_URL.PATTERNFLY_ORG + 'content-views/',
  REACT_BOOTSTRAP_COMPONENT: BASE_URL.REACT_BOOTSTRAP + 'components/',
  REACT_BOOTSTRAP_LAYOUT: BASE_URL.REACT_BOOTSTRAP + 'layout/'
};
