/* eslint-disable camelcase */
import chart_theme_multi_color_unordered_ColorScale_100 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_100';
import chart_theme_multi_color_unordered_ColorScale_200 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_200';
import chart_theme_multi_color_unordered_ColorScale_300 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_300';
import chart_theme_multi_color_unordered_ColorScale_400 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_400';
import chart_theme_multi_color_unordered_ColorScale_500 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_500';
import chart_theme_multi_color_unordered_ColorScale_600 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_600';
import chart_theme_multi_color_unordered_ColorScale_700 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_700';
import chart_theme_multi_color_unordered_ColorScale_800 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_800';
import chart_theme_multi_color_unordered_ColorScale_900 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_900';
import chart_theme_multi_color_unordered_ColorScale_1000 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1000';
import chart_theme_multi_color_unordered_ColorScale_1100 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1100';
import chart_theme_multi_color_unordered_ColorScale_1200 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1200';
import chart_theme_multi_color_unordered_ColorScale_1300 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1300';
import chart_theme_multi_color_unordered_ColorScale_1400 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1400';
import chart_theme_multi_color_unordered_ColorScale_1500 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1500';
import chart_theme_multi_color_unordered_ColorScale_1600 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1600';
import chart_theme_multi_color_unordered_ColorScale_1700 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1700';
import chart_theme_multi_color_unordered_ColorScale_1800 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1800';
import chart_theme_multi_color_unordered_ColorScale_1900 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_1900';
import chart_theme_multi_color_unordered_ColorScale_2000 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2000';
import chart_theme_multi_color_unordered_ColorScale_2100 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2100';
import chart_theme_multi_color_unordered_ColorScale_2200 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2200';
import chart_theme_multi_color_unordered_ColorScale_2300 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2300';
import chart_theme_multi_color_unordered_ColorScale_2400 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2400';
import chart_theme_multi_color_unordered_ColorScale_2500 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2500';
import chart_theme_multi_color_unordered_ColorScale_2600 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2600';
import chart_theme_multi_color_unordered_ColorScale_2700 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2700';
import chart_theme_multi_color_unordered_ColorScale_2800 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2800';
import chart_theme_multi_color_unordered_ColorScale_2900 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_2900';
import chart_theme_multi_color_unordered_ColorScale_3000 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_3000';
import chart_theme_multi_color_unordered_ColorScale_3100 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_3100';
import chart_theme_multi_color_unordered_ColorScale_3200 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_3200';
import chart_theme_multi_color_unordered_ColorScale_3300 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_3300';
import chart_theme_multi_color_unordered_ColorScale_3400 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_3400';
import chart_theme_multi_color_unordered_ColorScale_3500 from '@patternfly/react-tokens/dist/esm/chart_theme_multi_color_unordered_ColorScale_3500';
import { ColorTheme } from '../color-theme';

// The color order below improves the color contrast in unordered charts; area & line
// See https://github.com/patternfly/patternfly-next/issues/1551
const COLOR_SCALE = [
  chart_theme_multi_color_unordered_ColorScale_100.var,
  chart_theme_multi_color_unordered_ColorScale_200.var,
  chart_theme_multi_color_unordered_ColorScale_300.var,
  chart_theme_multi_color_unordered_ColorScale_400.var,
  chart_theme_multi_color_unordered_ColorScale_500.var,
  chart_theme_multi_color_unordered_ColorScale_600.var,
  chart_theme_multi_color_unordered_ColorScale_700.var,
  chart_theme_multi_color_unordered_ColorScale_800.var,
  chart_theme_multi_color_unordered_ColorScale_900.var,
  chart_theme_multi_color_unordered_ColorScale_1000.var,
  chart_theme_multi_color_unordered_ColorScale_1100.var,
  chart_theme_multi_color_unordered_ColorScale_1200.var,
  chart_theme_multi_color_unordered_ColorScale_1300.var,
  chart_theme_multi_color_unordered_ColorScale_1400.var,
  chart_theme_multi_color_unordered_ColorScale_1500.var,
  chart_theme_multi_color_unordered_ColorScale_1600.var,
  chart_theme_multi_color_unordered_ColorScale_1700.var,
  chart_theme_multi_color_unordered_ColorScale_1800.var,
  chart_theme_multi_color_unordered_ColorScale_1900.var,
  chart_theme_multi_color_unordered_ColorScale_2000.var,
  chart_theme_multi_color_unordered_ColorScale_2100.var,
  chart_theme_multi_color_unordered_ColorScale_2200.var,
  chart_theme_multi_color_unordered_ColorScale_2300.var,
  chart_theme_multi_color_unordered_ColorScale_2400.var,
  chart_theme_multi_color_unordered_ColorScale_2500.var,
  chart_theme_multi_color_unordered_ColorScale_2600.var,
  chart_theme_multi_color_unordered_ColorScale_2700.var,
  chart_theme_multi_color_unordered_ColorScale_2800.var,
  chart_theme_multi_color_unordered_ColorScale_2900.var,
  chart_theme_multi_color_unordered_ColorScale_3000.var,
  chart_theme_multi_color_unordered_ColorScale_3100.var,
  chart_theme_multi_color_unordered_ColorScale_3200.var,
  chart_theme_multi_color_unordered_ColorScale_3300.var,
  chart_theme_multi_color_unordered_ColorScale_3400.var,
  chart_theme_multi_color_unordered_ColorScale_3500.var
];

export const DarkMultiColorUnorderedTheme = ColorTheme({
  COLOR_SCALE
});
