import React from "react";
import {
  AddCircleOIcon, AngleDoubleLeftIcon, AngleDoubleRightIcon, AngleDownIcon, // ... other icons
} from "../generated";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by the figmaConnector script --
 * This file connects icon components to their corresponding Figma components.
 */

figma.connect(
  AddCircleOIcon,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=243-706&m=dev",
  {
    props: {
      // Example of adding icon-specific props
      size: figma.enum('Icon Size', {
        'Small': 'sm',
        'Medium': 'md',
        'Large': 'lg'
      }),
      className: figma.string('Additional CSS Classes')
    },
    example: (props) => (
      <AddCircleOIcon
        size={props.size}
        className={props.className}
      />
    )
  }
);

figma.connect(
  AngleDoubleLeftIcon,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=243-831&m=dev",
  {
    props: {
      // Example of adding icon-specific props
      size: figma.enum('Icon Size', {
        'Small': 'sm',
        'Medium': 'md',
        'Large': 'lg'
      }),
      className: figma.string('Additional CSS Classes')
    },
    example: (props) => (
      <AngleDoubleLeftIcon
        size={props.size}
        className={props.className}
      />
    )
  }
);

figma.connect(
  AngleDoubleRightIcon,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=243-856&m=dev",
  {
    props: {
      // Example of adding icon-specific props
      size: figma.enum('Icon Size', {
        'Small': 'sm',
        'Medium': 'md',
        'Large': 'lg'
      }),
      className: figma.string('Additional CSS Classes')
    },
    example: (props) => (
      <AngleDoubleRightIcon
        size={props.size}
        className={props.className}
      />
    )
  }
);

figma.connect(
  AngleDownIcon,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6%3A-Components-Test?node-id=243-845&m=dev",
  {
    props: {
      // Example of adding icon-specific props
      size: figma.enum('Icon Size', {
        'Small': 'sm',
        'Medium': 'md',
        'Large': 'lg'
      }),
      className: figma.string('Additional CSS Classes')
    },
    example: (props) => (
      <AngleDownIcon
        size={props.size}
        className={props.className}
      />
    )
  }
);

figma.connect(
  // ... other icons,
  "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?node-id=1-196&m=dev",
  {
    props: {
      // Example of adding icon-specific props
      size: figma.enum('Icon Size', {
        'Small': 'sm',
        'Medium': 'md',
        'Large': 'lg'
      }),
      className: figma.string('Additional CSS Classes')
    },
    example: (props) => (
      <// ... other icons
        size={props.size}
        className={props.className}
      />
    )
  }
);
