
import {
  AddCircleOIcon, AngleDoubleLeftIcon, AngleDoubleRightIcon, AngleDownIcon, AngleLeftIcon, AngleRightIcon, AngleUpIcon, AnsibleIcon, ArrowCircleDownIcon, ArrowCircleUpIcon, ArrowRightIcon, ArrowsAltVIcon, AsleepIcon, AttentionBellIcon, AutomationIcon, BalanceScaleIcon, BanIcon, BarsIcon, BellIcon, BitbucketIcon, BlueprintIcon, BugIcon, BuildIcon, BuilderImageIcon, BundleIcon, CalendarIcon, CaretDownIcon, CatalogIcon, CheckCircle2xlIcon, CheckCircleIcon, CheckIcon, ClipboardCheckIcon, ClockIcon, CloudSecurityIcon, CloudTenantIcon, ClusterIcon, CodeBranchIcon, CodeIcon, CogIcon, CogsIcon, ColumnsIcon, CommentsIcon, CompressArrowsAltIcon, CompressIcon, ConnectedIcon, CopyIcon, CubeIcon, CubesIcon, DataProcessorIcon, DataSinkIcon, DataSourceIcon, DatabaseIcon, DegradedIcon, DesktopIcon, DisconnectedIcon, DomainIcon, DownLeftAndUpRightToCenterSolidIcon, DownloadIcon, DropboxIcon, DrupalIcon, EllipsisVIcon, EnhancementIcon, EnterpriseIcon, ExclamationCircleIcon, ExclamationTriangleIcon, ExpandArrowsAltIcon, ExpandIcon, ExportIcon, ExternalLinkAltIcon, EyeIcon, EyeSlashIcon, FacebookIcon, FileIcon, FilterIcon, FingerprintIcon, FlagIcon, FlavorIcon, FolderIcon, FolderOpenIcon, GithubIcon, GitlabIcon, GoogleIcon, GripHorizontalIcon, GripVerticalIcon, HardDriveIcon, HddIcon, HistoryIcon, HomeIcon, ImageIcon, ImportIcon, InProgressIcon, InfoCircleIcon, InfrastructureIcon, IntegrationIcon, JsIcon, KeyIcon, LinkedinIcon, LinuxIcon, ListIcon, LockIcon, LockOpenIcon, LongArrowAltDownIcon, LongArrowAltUpIcon, MapMarkerIcon, MemoryIcon, MessageIcon, MicrochipIcon, MicrophoneIcon, MiddlewareIcon, MigrationIcon, MinusCircleIcon, MinusIcon, MonitoringIcon, MulticlusterIcon, NetworkIcon, NetworkRangeIcon, NewProcessIcon, NotStartedIcon, OffIcon, OpenDrawerRightIcon, OpenshiftIcon, OpenstackIcon, OptimizeIcon, PanelCloseIcon, PanelOpenIcon, PaperPlaneIcon, PaperclipIcon, PatternflyIcon, PauseCircleIcon, PauseIcon, PencilAltIcon, PendingIcon, PlayIcon, PlusCircleIcon, PlusIcon, PortIcon, PowerOffIcon, PrintIcon, PrivateIcon, ProcessAutomationIcon, QuestionCircleIcon, RedoIcon, RegionsIcon, RegistryIcon, ReplicatorIcon, RepositoryIcon, ResourcePoolIcon, ResourcesAlmostEmptyIcon, ResourcesAlmostFullIcon, ResourcesEmptyIcon, ResourcesFullIcon, RobotIcon, RouteIcon, RunningIcon, SatelliteIcon, SaveIcon, SearchIcon, SearchMinusIcon, SearchPlusIcon, SecurityIcon, ServerGroupIcon, ServiceCatalogIcon, ServiceIcon, ServicesIcon, SeverityCriticalIcon, SeverityImportantIcon, SeverityMinorIcon, SeverityModerateIcon, SeverityNoneIcon, SeverityUnidentifiedIcon, ShareSquareIcon, ShareSquareOutlineIcon, SlidersIcon, SortAmountDownAltIcon, SortAmountDownIcon, SpaceShuttle2xlIcon, StackOverflowIcon, StarIcon, StopIcon, StorageDomainIcon, SyncAltIcon, TableIcon, TachometerAltIcon, TagIcon, TaskIcon, TemplateIcon, TenantIcon, ThIcon, ThLargeIcon, ThumbsDownIcon, ThumbsDownRegularIcon, ThumbsUpIcon, ThumbsUpRegularIcon, ThumbtackIcon, TimesCircleIcon, TimesIcon, TopologyIcon, TrashIcon, TreeviewIcon, TrendDownIcon, TrendUpIcon, TwitterIcon, UndoIcon, UnknownIcon, UpRightAndDownLeftFromCenterSolidIcon, UploadIcon, UserIcon, VcenterIcon, VirtualMachineIcon, VolumeHighIcon, VolumeIcon, WindowRestoreIcon, WindowsIcon, WrenchIcon, ZoneIcon
} from "./@patternfly/react-icons";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by the figmaConnector script --
 * This file connects icon components to their corresponding Figma components.
 */

figma.connect(AddCircleOIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-706&m=dev", {
  props: {},
  example: (props) => <AddCircleOIcon {...props} />
});

figma.connect(AngleDoubleLeftIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-831&m=dev", {
  props: {},
  example: (props) => <AngleDoubleLeftIcon {...props} />
});

figma.connect(AngleDoubleRightIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-856&m=dev", {
  props: {},
  example: (props) => <AngleDoubleRightIcon {...props} />
});

figma.connect(AngleDownIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-845&m=dev", {
  props: {},
  example: (props) => <AngleDownIcon {...props} />
});

figma.connect(AngleLeftIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-844&m=dev", {
  props: {},
  example: (props) => <AngleLeftIcon {...props} />
});

figma.connect(AngleRightIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-837&m=dev", {
  props: {},
  example: (props) => <AngleRightIcon {...props} />
});

figma.connect(AngleUpIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-834&m=dev", {
  props: {},
  example: (props) => <AngleUpIcon {...props} />
});

figma.connect(AnsibleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8770&m=dev", {
  props: {},
  example: (props) => <AnsibleIcon {...props} />
});

figma.connect(ArrowCircleDownIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-571&m=dev", {
  props: {},
  example: (props) => <ArrowCircleDownIcon {...props} />
});

figma.connect(ArrowCircleUpIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-582&m=dev", {
  props: {},
  example: (props) => <ArrowCircleUpIcon {...props} />
});

figma.connect(ArrowRightIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-852&m=dev", {
  props: {},
  example: (props) => <ArrowRightIcon {...props} />
});

figma.connect(ArrowsAltVIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-847&m=dev", {
  props: {},
  example: (props) => <ArrowsAltVIcon {...props} />
});

figma.connect(AsleepIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-579&m=dev", {
  props: {},
  example: (props) => <AsleepIcon {...props} />
});

figma.connect(AttentionBellIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-551&m=dev", {
  props: {},
  example: (props) => <AttentionBellIcon {...props} />
});

figma.connect(AutomationIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-823&m=dev", {
  props: {},
  example: (props) => <AutomationIcon {...props} />
});

figma.connect(BalanceScaleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-560&m=dev", {
  props: {},
  example: (props) => <BalanceScaleIcon {...props} />
});

figma.connect(BanIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-580&m=dev", {
  props: {},
  example: (props) => <BanIcon {...props} />
});

figma.connect(BarsIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-841&m=dev", {
  props: {},
  example: (props) => <BarsIcon {...props} />
});

figma.connect(BellIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-562&m=dev", {
  props: {},
  example: (props) => <BellIcon {...props} />
});

figma.connect(BitbucketIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=947-4061&m=dev", {
  props: {},
  example: (props) => <BitbucketIcon {...props} />
});

figma.connect(BlueprintIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-795&m=dev", {
  props: {},
  example: (props) => <BlueprintIcon {...props} />
});

figma.connect(BugIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-549&m=dev", {
  props: {},
  example: (props) => <BugIcon {...props} />
});

figma.connect(BuildIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-828&m=dev", {
  props: {},
  example: (props) => <BuildIcon {...props} />
});

figma.connect(BuilderImageIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-824&m=dev", {
  props: {},
  example: (props) => <BuilderImageIcon {...props} />
});

figma.connect(BundleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-806&m=dev", {
  props: {},
  example: (props) => <BundleIcon {...props} />
});

figma.connect(CalendarIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-855&m=dev", {
  props: {},
  example: (props) => <CalendarIcon {...props} />
});

figma.connect(CaretDownIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-835&m=dev", {
  props: {},
  example: (props) => <CaretDownIcon {...props} />
});

figma.connect(CatalogIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-784&m=dev", {
  props: {},
  example: (props) => <CatalogIcon {...props} />
});

figma.connect(CheckCircle2xlIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=1179-74&m=dev", {
  props: {},
  example: (props) => <CheckCircle2xlIcon {...props} />
});

figma.connect(CheckCircleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=1179-71&m=dev", {
  props: {},
  example: (props) => <CheckCircleIcon {...props} />
});

figma.connect(CheckIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-747&m=dev", {
  props: {},
  example: (props) => <CheckIcon {...props} />
});

figma.connect(ClipboardCheckIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-822&m=dev", {
  props: {},
  example: (props) => <ClipboardCheckIcon {...props} />
});

figma.connect(ClockIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-843&m=dev", {
  props: {},
  example: (props) => <ClockIcon {...props} />
});

figma.connect(CloudSecurityIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-802&m=dev", {
  props: {},
  example: (props) => <CloudSecurityIcon {...props} />
});

figma.connect(CloudTenantIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-814&m=dev", {
  props: {},
  example: (props) => <CloudTenantIcon {...props} />
});

figma.connect(ClusterIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-809&m=dev", {
  props: {},
  example: (props) => <ClusterIcon {...props} />
});

figma.connect(CodeBranchIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-825&m=dev", {
  props: {},
  example: (props) => <CodeBranchIcon {...props} />
});

figma.connect(CodeIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-829&m=dev", {
  props: {},
  example: (props) => <CodeIcon {...props} />
});

figma.connect(CogIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-732&m=dev", {
  props: {},
  example: (props) => <CogIcon {...props} />
});

figma.connect(CogsIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=25229-2108&m=dev", {
  props: {},
  example: (props) => <CogsIcon {...props} />
});

figma.connect(ColumnsIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-741&m=dev", {
  props: {},
  example: (props) => <ColumnsIcon {...props} />
});

figma.connect(CommentsIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-849&m=dev", {
  props: {},
  example: (props) => <CommentsIcon {...props} />
});

figma.connect(CompressArrowsAltIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-726&m=dev", {
  props: {},
  example: (props) => <CompressArrowsAltIcon {...props} />
});

figma.connect(CompressIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-731&m=dev", {
  props: {},
  example: (props) => <CompressIcon {...props} />
});

figma.connect(ConnectedIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-576&m=dev", {
  props: {},
  example: (props) => <ConnectedIcon {...props} />
});

figma.connect(CopyIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-727&m=dev", {
  props: {},
  example: (props) => <CopyIcon {...props} />
});

figma.connect(CubeIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-808&m=dev", {
  props: {},
  example: (props) => <CubeIcon {...props} />
});

figma.connect(CubesIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=1179-51&m=dev", {
  props: {},
  example: (props) => <CubesIcon {...props} />
});

figma.connect(DataProcessorIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=955-4123&m=dev", {
  props: {},
  example: (props) => <DataProcessorIcon {...props} />
});

figma.connect(DataSinkIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=955-4105&m=dev", {
  props: {},
  example: (props) => <DataSinkIcon {...props} />
});

figma.connect(DataSourceIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=955-4122&m=dev", {
  props: {},
  example: (props) => <DataSourceIcon {...props} />
});

figma.connect(DatabaseIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-816&m=dev", {
  props: {},
  example: (props) => <DatabaseIcon {...props} />
});

figma.connect(DegradedIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-561&m=dev", {
  props: {},
  example: (props) => <DegradedIcon {...props} />
});

figma.connect(DesktopIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-807&m=dev", {
  props: {},
  example: (props) => <DesktopIcon {...props} />
});

figma.connect(DisconnectedIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-558&m=dev", {
  props: {},
  example: (props) => <DisconnectedIcon {...props} />
});

figma.connect(DomainIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-797&m=dev", {
  props: {},
  example: (props) => <DomainIcon {...props} />
});

figma.connect(DownLeftAndUpRightToCenterSolidIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=13488-1851&m=dev", {
  props: {},
  example: (props) => <DownLeftAndUpRightToCenterSolidIcon {...props} />
});

figma.connect(DownloadIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-724&m=dev", {
  props: {},
  example: (props) => <DownloadIcon {...props} />
});

figma.connect(DropboxIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8761&m=dev", {
  props: {},
  example: (props) => <DropboxIcon {...props} />
});

figma.connect(DrupalIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8758&m=dev", {
  props: {},
  example: (props) => <DrupalIcon {...props} />
});

figma.connect(EllipsisVIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-839&m=dev", {
  props: {},
  example: (props) => <EllipsisVIcon {...props} />
});

figma.connect(EnhancementIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-554&m=dev", {
  props: {},
  example: (props) => <EnhancementIcon {...props} />
});

figma.connect(EnterpriseIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-812&m=dev", {
  props: {},
  example: (props) => <EnterpriseIcon {...props} />
});

figma.connect(ExclamationCircleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-566&m=dev", {
  props: {},
  example: (props) => <ExclamationCircleIcon {...props} />
});

figma.connect(ExclamationTriangleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=1179-52&m=dev", {
  props: {},
  example: (props) => <ExclamationTriangleIcon {...props} />
});

figma.connect(ExpandArrowsAltIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-720&m=dev", {
  props: {},
  example: (props) => <ExpandArrowsAltIcon {...props} />
});

figma.connect(ExpandIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-728&m=dev", {
  props: {},
  example: (props) => <ExpandIcon {...props} />
});

figma.connect(ExportIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-744&m=dev", {
  props: {},
  example: (props) => <ExportIcon {...props} />
});

figma.connect(ExternalLinkAltIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-734&m=dev", {
  props: {},
  example: (props) => <ExternalLinkAltIcon {...props} />
});

figma.connect(EyeIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-851&m=dev", {
  props: {},
  example: (props) => <EyeIcon {...props} />
});

figma.connect(EyeSlashIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-836&m=dev", {
  props: {},
  example: (props) => <EyeSlashIcon {...props} />
});

figma.connect(FacebookIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8763&m=dev", {
  props: {},
  example: (props) => <FacebookIcon {...props} />
});

figma.connect(FileIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=955-4139&m=dev", {
  props: {},
  example: (props) => <FileIcon {...props} />
});

figma.connect(FilterIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-733&m=dev", {
  props: {},
  example: (props) => <FilterIcon {...props} />
});

figma.connect(FingerprintIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-175&m=dev", {
  props: {},
  example: (props) => <FingerprintIcon {...props} />
});

figma.connect(FlagIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-789&m=dev", {
  props: {},
  example: (props) => <FlagIcon {...props} />
});

figma.connect(FlavorIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-799&m=dev", {
  props: {},
  example: (props) => <FlavorIcon {...props} />
});

figma.connect(FolderIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-838&m=dev", {
  props: {},
  example: (props) => <FolderIcon {...props} />
});

figma.connect(FolderOpenIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-857&m=dev", {
  props: {},
  example: (props) => <FolderOpenIcon {...props} />
});

figma.connect(GithubIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8764&m=dev", {
  props: {},
  example: (props) => <GithubIcon {...props} />
});

figma.connect(GitlabIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8771&m=dev", {
  props: {},
  example: (props) => <GitlabIcon {...props} />
});

figma.connect(GoogleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8768&m=dev", {
  props: {},
  example: (props) => <GoogleIcon {...props} />
});

figma.connect(GripHorizontalIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-830&m=dev", {
  props: {},
  example: (props) => <GripHorizontalIcon {...props} />
});

figma.connect(GripVerticalIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-854&m=dev", {
  props: {},
  example: (props) => <GripVerticalIcon {...props} />
});

figma.connect(HardDriveIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-179&m=dev", {
  props: {},
  example: (props) => <HardDriveIcon {...props} />
});

figma.connect(HddIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-818&m=dev", {
  props: {},
  example: (props) => <HddIcon {...props} />
});

figma.connect(HistoryIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-556&m=dev", {
  props: {},
  example: (props) => <HistoryIcon {...props} />
});

figma.connect(HomeIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-848&m=dev", {
  props: {},
  example: (props) => <HomeIcon {...props} />
});

figma.connect(ImageIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-821&m=dev", {
  props: {},
  example: (props) => <ImageIcon {...props} />
});

figma.connect(ImportIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-718&m=dev", {
  props: {},
  example: (props) => <ImportIcon {...props} />
});

figma.connect(InProgressIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-552&m=dev", {
  props: {},
  example: (props) => <InProgressIcon {...props} />
});

figma.connect(InfoCircleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-550&m=dev", {
  props: {},
  example: (props) => <InfoCircleIcon {...props} />
});

figma.connect(InfrastructureIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-800&m=dev", {
  props: {},
  example: (props) => <InfrastructureIcon {...props} />
});

figma.connect(IntegrationIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-805&m=dev", {
  props: {},
  example: (props) => <IntegrationIcon {...props} />
});

figma.connect(JsIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8759&m=dev", {
  props: {},
  example: (props) => <JsIcon {...props} />
});

figma.connect(KeyIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-826&m=dev", {
  props: {},
  example: (props) => <KeyIcon {...props} />
});

figma.connect(LinkedinIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8760&m=dev", {
  props: {},
  example: (props) => <LinkedinIcon {...props} />
});

figma.connect(LinuxIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8765&m=dev", {
  props: {},
  example: (props) => <LinuxIcon {...props} />
});

figma.connect(ListIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-661&m=dev", {
  props: {},
  example: (props) => <ListIcon {...props} />
});

figma.connect(LockIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-584&m=dev", {
  props: {},
  example: (props) => <LockIcon {...props} />
});

figma.connect(LockOpenIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-564&m=dev", {
  props: {},
  example: (props) => <LockOpenIcon {...props} />
});

figma.connect(LongArrowAltDownIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-842&m=dev", {
  props: {},
  example: (props) => <LongArrowAltDownIcon {...props} />
});

figma.connect(LongArrowAltUpIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-858&m=dev", {
  props: {},
  example: (props) => <LongArrowAltUpIcon {...props} />
});

figma.connect(MapMarkerIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-853&m=dev", {
  props: {},
  example: (props) => <MapMarkerIcon {...props} />
});

figma.connect(MemoryIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-817&m=dev", {
  props: {},
  example: (props) => <MemoryIcon {...props} />
});

figma.connect(MessageIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30046-208&m=dev", {
  props: {},
  example: (props) => <MessageIcon {...props} />
});

figma.connect(MicrochipIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-815&m=dev", {
  props: {},
  example: (props) => <MicrochipIcon {...props} />
});

figma.connect(MicrophoneIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30379&m=dev", {
  props: {},
  example: (props) => <MicrophoneIcon {...props} />
});

figma.connect(MiddlewareIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-791&m=dev", {
  props: {},
  example: (props) => <MiddlewareIcon {...props} />
});

figma.connect(MigrationIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-559&m=dev", {
  props: {},
  example: (props) => <MigrationIcon {...props} />
});

figma.connect(MinusCircleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-715&m=dev", {
  props: {},
  example: (props) => <MinusCircleIcon {...props} />
});

figma.connect(MinusIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-740&m=dev", {
  props: {},
  example: (props) => <MinusIcon {...props} />
});

figma.connect(MonitoringIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-794&m=dev", {
  props: {},
  example: (props) => <MonitoringIcon {...props} />
});

figma.connect(MulticlusterIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=955-4124&m=dev", {
  props: {},
  example: (props) => <MulticlusterIcon {...props} />
});

figma.connect(NetworkIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-804&m=dev", {
  props: {},
  example: (props) => <NetworkIcon {...props} />
});

figma.connect(NetworkRangeIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-788&m=dev", {
  props: {},
  example: (props) => <NetworkRangeIcon {...props} />
});

figma.connect(NewProcessIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-581&m=dev", {
  props: {},
  example: (props) => <NewProcessIcon {...props} />
});

figma.connect(NotStartedIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-545&m=dev", {
  props: {},
  example: (props) => <NotStartedIcon {...props} />
});

figma.connect(OffIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-553&m=dev", {
  props: {},
  example: (props) => <OffIcon {...props} />
});

figma.connect(OpenDrawerRightIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=1322-74&m=dev", {
  props: {},
  example: (props) => <OpenDrawerRightIcon {...props} />
});

figma.connect(OpenshiftIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8773&m=dev", {
  props: {},
  example: (props) => <OpenshiftIcon {...props} />
});

figma.connect(OpenstackIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8769&m=dev", {
  props: {},
  example: (props) => <OpenstackIcon {...props} />
});

figma.connect(OptimizeIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-713&m=dev", {
  props: {},
  example: (props) => <OptimizeIcon {...props} />
});

figma.connect(PanelCloseIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-711&m=dev", {
  props: {},
  example: (props) => <PanelCloseIcon {...props} />
});

figma.connect(PanelOpenIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-721&m=dev", {
  props: {},
  example: (props) => <PanelOpenIcon {...props} />
});

figma.connect(PaperPlaneIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30373&m=dev", {
  props: {},
  example: (props) => <PaperPlaneIcon {...props} />
});

figma.connect(PaperclipIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-164&m=dev", {
  props: {},
  example: (props) => <PaperclipIcon {...props} />
});

figma.connect(PatternflyIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8757&m=dev", {
  props: {},
  example: (props) => <PatternflyIcon {...props} />
});

figma.connect(PauseCircleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-578&m=dev", {
  props: {},
  example: (props) => <PauseCircleIcon {...props} />
});

figma.connect(PauseIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-746&m=dev", {
  props: {},
  example: (props) => <PauseIcon {...props} />
});

figma.connect(PencilAltIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-729&m=dev", {
  props: {},
  example: (props) => <PencilAltIcon {...props} />
});

figma.connect(PendingIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-570&m=dev", {
  props: {},
  example: (props) => <PendingIcon {...props} />
});

figma.connect(PlayIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-736&m=dev", {
  props: {},
  example: (props) => <PlayIcon {...props} />
});

figma.connect(PlusCircleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=1179-79&m=dev", {
  props: {},
  example: (props) => <PlusCircleIcon {...props} />
});

figma.connect(PlusIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-708&m=dev", {
  props: {},
  example: (props) => <PlusIcon {...props} />
});

figma.connect(PortIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-796&m=dev", {
  props: {},
  example: (props) => <PortIcon {...props} />
});

figma.connect(PowerOffIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-577&m=dev", {
  props: {},
  example: (props) => <PowerOffIcon {...props} />
});

figma.connect(PrintIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-725&m=dev", {
  props: {},
  example: (props) => <PrintIcon {...props} />
});

figma.connect(PrivateIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-565&m=dev", {
  props: {},
  example: (props) => <PrivateIcon {...props} />
});

figma.connect(ProcessAutomationIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-792&m=dev", {
  props: {},
  example: (props) => <ProcessAutomationIcon {...props} />
});

figma.connect(QuestionCircleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-850&m=dev", {
  props: {},
  example: (props) => <QuestionCircleIcon {...props} />
});

figma.connect(RedoIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-707&m=dev", {
  props: {},
  example: (props) => <RedoIcon {...props} />
});

figma.connect(RegionsIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-786&m=dev", {
  props: {},
  example: (props) => <RegionsIcon {...props} />
});

figma.connect(RegistryIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-801&m=dev", {
  props: {},
  example: (props) => <RegistryIcon {...props} />
});

figma.connect(ReplicatorIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-787&m=dev", {
  props: {},
  example: (props) => <ReplicatorIcon {...props} />
});

figma.connect(RepositoryIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-785&m=dev", {
  props: {},
  example: (props) => <RepositoryIcon {...props} />
});

figma.connect(ResourcePoolIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-811&m=dev", {
  props: {},
  example: (props) => <ResourcePoolIcon {...props} />
});

figma.connect(ResourcesAlmostEmptyIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-547&m=dev", {
  props: {},
  example: (props) => <ResourcesAlmostEmptyIcon {...props} />
});

figma.connect(ResourcesAlmostFullIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-575&m=dev", {
  props: {},
  example: (props) => <ResourcesAlmostFullIcon {...props} />
});

figma.connect(ResourcesEmptyIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-548&m=dev", {
  props: {},
  example: (props) => <ResourcesEmptyIcon {...props} />
});

figma.connect(ResourcesFullIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-546&m=dev", {
  props: {},
  example: (props) => <ResourcesFullIcon {...props} />
});

figma.connect(RobotIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-171&m=dev", {
  props: {},
  example: (props) => <RobotIcon {...props} />
});

figma.connect(RouteIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-803&m=dev", {
  props: {},
  example: (props) => <RouteIcon {...props} />
});

figma.connect(RunningIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-568&m=dev", {
  props: {},
  example: (props) => <RunningIcon {...props} />
});

figma.connect(SatelliteIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8766&m=dev", {
  props: {},
  example: (props) => <SatelliteIcon {...props} />
});

figma.connect(SaveIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-712&m=dev", {
  props: {},
  example: (props) => <SaveIcon {...props} />
});

figma.connect(SearchIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-730&m=dev", {
  props: {},
  example: (props) => <SearchIcon {...props} />
});

figma.connect(SearchMinusIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-743&m=dev", {
  props: {},
  example: (props) => <SearchMinusIcon {...props} />
});

figma.connect(SearchPlusIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-739&m=dev", {
  props: {},
  example: (props) => <SearchPlusIcon {...props} />
});

figma.connect(SecurityIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-574&m=dev", {
  props: {},
  example: (props) => <SecurityIcon {...props} />
});

figma.connect(ServerGroupIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-782&m=dev", {
  props: {},
  example: (props) => <ServerGroupIcon {...props} />
});

figma.connect(ServiceCatalogIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-810&m=dev", {
  props: {},
  example: (props) => <ServiceCatalogIcon {...props} />
});

figma.connect(ServiceIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-820&m=dev", {
  props: {},
  example: (props) => <ServiceIcon {...props} />
});

figma.connect(ServicesIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-819&m=dev", {
  props: {},
  example: (props) => <ServicesIcon {...props} />
});

figma.connect(SeverityCriticalIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=24002-223128&m=dev", {
  props: {},
  example: (props) => <SeverityCriticalIcon {...props} />
});

figma.connect(SeverityImportantIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=24000-218644&m=dev", {
  props: {},
  example: (props) => <SeverityImportantIcon {...props} />
});

figma.connect(SeverityMinorIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=24000-218665&m=dev", {
  props: {},
  example: (props) => <SeverityMinorIcon {...props} />
});

figma.connect(SeverityModerateIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=24000-218695&m=dev", {
  props: {},
  example: (props) => <SeverityModerateIcon {...props} />
});

figma.connect(SeverityNoneIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=24000-218672&m=dev", {
  props: {},
  example: (props) => <SeverityNoneIcon {...props} />
});

figma.connect(SeverityUnidentifiedIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=24000-218676&m=dev", {
  props: {},
  example: (props) => <SeverityUnidentifiedIcon {...props} />
});

figma.connect(ShareSquareIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-737&m=dev", {
  props: {},
  example: (props) => <ShareSquareIcon {...props} />
});

figma.connect(ShareSquareOutlineIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30057-266018&m=dev", {
  props: {},
  example: (props) => <ShareSquareOutlineIcon {...props} />
});

figma.connect(SlidersIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30370&m=dev", {
  props: {},
  example: (props) => <SlidersIcon {...props} />
});

figma.connect(SortAmountDownAltIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-745&m=dev", {
  props: {},
  example: (props) => <SortAmountDownAltIcon {...props} />
});

figma.connect(SortAmountDownIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-735&m=dev", {
  props: {},
  example: (props) => <SortAmountDownIcon {...props} />
});

figma.connect(SpaceShuttle2xlIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-862&m=dev", {
  props: {},
  example: (props) => <SpaceShuttle2xlIcon {...props} />
});

figma.connect(StackOverflowIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8767&m=dev", {
  props: {},
  example: (props) => <StackOverflowIcon {...props} />
});

figma.connect(StarIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-776&m=dev", {
  props: {},
  example: (props) => <StarIcon {...props} />
});

figma.connect(StopIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30382&m=dev", {
  props: {},
  example: (props) => <StopIcon {...props} />
});

figma.connect(StorageDomainIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-793&m=dev", {
  props: {},
  example: (props) => <StorageDomainIcon {...props} />
});

figma.connect(SyncAltIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-723&m=dev", {
  props: {},
  example: (props) => <SyncAltIcon {...props} />
});

figma.connect(TableIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-659&m=dev", {
  props: {},
  example: (props) => <TableIcon {...props} />
});

figma.connect(TachometerAltIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-660&m=dev", {
  props: {},
  example: (props) => <TachometerAltIcon {...props} />
});

figma.connect(TagIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-813&m=dev", {
  props: {},
  example: (props) => <TagIcon {...props} />
});

figma.connect(TaskIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-833&m=dev", {
  props: {},
  example: (props) => <TaskIcon {...props} />
});

figma.connect(TemplateIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-783&m=dev", {
  props: {},
  example: (props) => <TemplateIcon {...props} />
});

figma.connect(TenantIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-778&m=dev", {
  props: {},
  example: (props) => <TenantIcon {...props} />
});

figma.connect(ThIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-658&m=dev", {
  props: {},
  example: (props) => <ThIcon {...props} />
});

figma.connect(ThLargeIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-657&m=dev", {
  props: {},
  example: (props) => <ThLargeIcon {...props} />
});

figma.connect(ThumbsDownIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30361&m=dev", {
  props: {},
  example: (props) => <ThumbsDownIcon {...props} />
});

figma.connect(ThumbsDownRegularIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30358&m=dev", {
  props: {},
  example: (props) => <ThumbsDownRegularIcon {...props} />
});

figma.connect(ThumbsUpIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30364&m=dev", {
  props: {},
  example: (props) => <ThumbsUpIcon {...props} />
});

figma.connect(ThumbsUpRegularIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30367&m=dev", {
  props: {},
  example: (props) => <ThumbsUpRegularIcon {...props} />
});

figma.connect(ThumbtackIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-832&m=dev", {
  props: {},
  example: (props) => <ThumbtackIcon {...props} />
});

figma.connect(TimesCircleIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-738&m=dev", {
  props: {},
  example: (props) => <TimesCircleIcon {...props} />
});

figma.connect(TimesIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-722&m=dev", {
  props: {},
  example: (props) => <TimesIcon {...props} />
});

figma.connect(TopologyIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-656&m=dev", {
  props: {},
  example: (props) => <TopologyIcon {...props} />
});

figma.connect(TrashIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-719&m=dev", {
  props: {},
  example: (props) => <TrashIcon {...props} />
});

figma.connect(TreeviewIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=501-2712&m=dev", {
  props: {},
  example: (props) => <TreeviewIcon {...props} />
});

figma.connect(TrendDownIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-563&m=dev", {
  props: {},
  example: (props) => <TrendDownIcon {...props} />
});

figma.connect(TrendUpIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-583&m=dev", {
  props: {},
  example: (props) => <TrendUpIcon {...props} />
});

figma.connect(TwitterIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8762&m=dev", {
  props: {},
  example: (props) => <TwitterIcon {...props} />
});

figma.connect(UndoIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-716&m=dev", {
  props: {},
  example: (props) => <UndoIcon {...props} />
});

figma.connect(UnknownIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-555&m=dev", {
  props: {},
  example: (props) => <UnknownIcon {...props} />
});

figma.connect(UpRightAndDownLeftFromCenterSolidIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=13274-2864&m=dev", {
  props: {},
  example: (props) => <UpRightAndDownLeftFromCenterSolidIcon {...props} />
});

figma.connect(UploadIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-714&m=dev", {
  props: {},
  example: (props) => <UploadIcon {...props} />
});

figma.connect(UserIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-790&m=dev", {
  props: {},
  example: (props) => <UserIcon {...props} />
});

figma.connect(VcenterIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-777&m=dev", {
  props: {},
  example: (props) => <VcenterIcon {...props} />
});

figma.connect(VirtualMachineIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-781&m=dev", {
  props: {},
  example: (props) => <VirtualMachineIcon {...props} />
});

figma.connect(VolumeHighIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=30048-30376&m=dev", {
  props: {},
  example: (props) => <VolumeHighIcon {...props} />
});

figma.connect(VolumeIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-780&m=dev", {
  props: {},
  example: (props) => <VolumeIcon {...props} />
});

figma.connect(WindowRestoreIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-742&m=dev", {
  props: {},
  example: (props) => <WindowRestoreIcon {...props} />
});

figma.connect(WindowsIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=242-8772&m=dev", {
  props: {},
  example: (props) => <WindowsIcon {...props} />
});

figma.connect(WrenchIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=1179-49&m=dev", {
  props: {},
  example: (props) => <WrenchIcon {...props} />
});

figma.connect(ZoneIcon, "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6%3A-Components?node-id=243-779&m=dev", {
  props: {},
  example: (props) => <ZoneIcon {...props} />
});
