// import React from "react"
// import { CheckboxInput } from "./CheckboxInput"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   CheckboxInput,
//   "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=157-1280&m=dev",
//   {
//     props: {},
//     example: (props) => <CheckboxInput />,
//   },
// )
