import figma from '@figma/code-connect';
import { FormGroup } from '@patternfly/react-core';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  FormGroup,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=17114-21566&m=dev',
  {
    props: {
      nestedOpen: figma.boolean('Nested - Open'),
      nestedNonExpandable: figma.boolean('Nested - Non expandable'),
      nestedClosed: figma.boolean('Nested - Closed'),
      children: figma.children('*')
    },
    example: (props) => <FormGroup>{props.children}</FormGroup>
  }
);
