// import React from "react"
// import { InputLabel } from "./InputLabel"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   InputLabel,
//   "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=151-1566&m=dev",
//   {
//     props: {
//       required: figma.boolean("Required"),
//       helpIcon: figma.boolean("Help icon"),
//       labelText: figma.string("Label text"),
//     },
//     example: (props) => <InputLabel />,
//   },
// )
