// import React from "react"
// import { LabeledInputGroup } from "./LabeledInputGroup"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   LabeledInputGroup,
//   "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=176-3526&m=dev",
//   {
//     props: {
//       label: figma.boolean("Label"),
//       helperText: figma.boolean("Helper text"),
//     },
//     example: (props) => <LabeledInputGroup />,
//   },
// )
