import React from 'react';
import { ToggleGroup } from './ToggleGroup';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  ToggleGroup,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=7644-56919',
  {
    props: {
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      })
    },
    example: (props) => <ToggleGroup />
  }
);

figma.connect(
  ToggleGroup,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2089-5606',
  {
    props: {
      hasText: figma.boolean('Has text'),
      hasIcon: figma.boolean('Has icon'),
      text: figma.string('Text'),
      position: figma.enum('Position', {
        Left: 'left',
        Middle: 'middle',
        RIght: 'right'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        Disabled: 'disabled'
      }),
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      })
    },
    example: (props) => <ToggleGroup />
  }
);
