import React from 'react';
import { Icon } from './Icon';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Icon, 'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=198-1573', {
  props: {
    icon: figma.instance('🖼️ Icon'),
    size: figma.enum('Icon Size', {
      'Standalone - Small': 'sm',
      'Standalone - Medium': 'md',
      'Standalone - Large': 'lg',
      'Standalone - XL': 'xl',
      'Standalone -2XL': '2xl',
      'Standalone - 3XL': '3xl',
      'Body - Small': 'bodySm',
      'Body - Default': 'bodyDefault',
      'Body - Large': 'bodyLg',
      'Heading - H1': 'heading_3xl',
      'Heading - H2': 'heading_2xl',
      'Heading - H3': 'headingXl',
      'Heading - H4': 'headingLg',
      'Heading - H5': 'headingMd',
      'Heading - H6': 'headingSm'
    })
  },
  example: ({ icon, ...props }) => <Icon {...props}>{icon}</Icon>
});
