import React from 'react';
import { Nav } from './Nav';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7119',
  {
    props: {
      hasIcon: figma.boolean('Has Icon'),
      Nav: figma.string('✏️ Nav item'),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected'
      }),
      type: figma.enum('Type', {
        Default: 'default',
        'Expandable - Open': 'expandable---open',
        'Expandable - Closed': 'expandable---closed',
        'With Flyout': 'with-flyout',
        'With Drilldown - Start': 'with-drilldown---start',
        'With Drilldown - Return': 'with-drilldown---return'
      })
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7233',
  {
    props: {
      showGroupHeader: figma.boolean('Show Group header')
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7117',
  {
    props: {
      headerTitle: figma.string('✏️ Header title')
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=7514-12157',
  {
    props: {
      showDivider: figma.boolean('Show divider'),
      showLeftOverflowArrow: figma.boolean('Show Left Overflow arrow'),
      showRightOverflowArrow: figma.boolean('Show Right Overflow arrow'),
      type: figma.enum('Type', {
        Main: 'main',
        Subnav: 'subnav'
      })
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7262',
  {
    props: {
      navItem: figma.string('✏️ Nav item'),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected'
      })
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7269',
  {
    props: {
      navItem: figma.string('✏️ Nav item'),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected'
      })
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7106',
  {
    props: {
      showProductTitleArea: figma.boolean('Show Product title area')
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7231',
  {
    props: {},
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7233',
  {
    props: {
      showGroupHeader: figma.boolean('Show Group header')
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7278',
  {
    props: {
      position: figma.enum('Position', {
        Left: 'left',
        Right: 'right'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Disabled: 'disabled'
      })
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7229',
  {
    props: {
      productName: figma.string('Product name')
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7174',
  {
    props: {
      navItem: figma.string('✏️ Nav item'),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected'
      }),
      expansion: figma.enum('Expansion', {
        'No expansion': 'no-expansion',
        'Expandable - Open': 'expandable---open',
        'Expandable - Closed': 'expandable---closed'
      })
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7283',
  {
    props: {
      position: figma.enum('Position', {
        Left: 'left',
        Right: 'right',
        Position3: 'position3',
        Position4: 'position4'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Disabled: 'disabled'
      })
    },
    example: (props) => <Nav />
  }
);

figma.connect(
  Nav,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2104-7254',
  {
    props: {
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected'
      })
    },
    example: (props) => <Nav />
  }
);
