import React from 'react';
import { TreeView } from './TreeView';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  TreeView,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=12615-2825',
  {
    props: {
      withSearch: figma.boolean('With Search'),
      type: figma.enum('Type', {
        Default: 'default',
        'separate selection & expansion': 'separate-selection---expansion',
        'With Branching': 'with-branching',
        'With Checkboxes': 'with-checkboxes',
        'With Icons': 'with-icons',
        'With Badges': 'with-badges',
        'With Actions': 'with-actions'
      })
    },
    example: (props) => <TreeView />
  }
);

figma.connect(
  TreeView,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=12615-3521',
  {
    props: {
      type: figma.enum('Type', {
        'With Background': 'with-background',
        'Without Background': 'without-background'
      })
    },
    example: (props) => <CompactTreeView />
  }
);

figma.connect(
  TreeView,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=12615-3269',
  {
    props: {
      withCheckbox: figma.boolean('With Checkbox'),
      noCaretIndent: figma.boolean('No Caret Indent'),
      showCaret: figma.boolean('Show Caret'),
      lvl3Indent: figma.boolean('Lvl 3 Indent'),
      text: figma.string('Text'),
      withActions: figma.boolean('With Actions'),
      defaultText: figma.boolean('Default Text'),
      lvl2Indent: figma.boolean('Lvl 2 Indent'),
      nodeGuide: figma.boolean('Node Guide'),
      lvl4Indent: figma.boolean('Lvl 4 Indent'),
      withIcon: figma.boolean('With Icon'),
      sepSelectionText: figma.boolean('Sep. Selection Text'),
      lvl1Indent: figma.boolean('Lvl 1 Indent'),
      endNodeGuide: figma.boolean('End Node Guide'),
      showBadge: figma.boolean('Show Badge')
    },
    example: (props) => <TreeView />
  }
);

figma.connect(
  TreeView,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=12615-3260',
  {
    props: {
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        'Expanded - Not Selected': 'expanded---not-selected'
      }),
      expandable: figma.boolean('Expandable')
    },
    example: (props) => <TreeView />
  }
);
