import { SFC, HTMLProps, ReactNode } from 'react';

export interface StyledFlexProps {
  className: string,
  children?: ReactNode,
  component: string,
  m?: number | string | Array<any>,
  mb?: number | string | Array<any>,
  ml?: number | string | Array<any>,
  mr?: number | string | Array<any>,
  mt?: number | string | Array<any>,
  mx?: number | string | Array<any>,
  my?: number | string | Array<any>,
  p?: number | string | Array<any>,
  pb?: number | string | Array<any>,
  pl?: number | string | Array<any>,
  pr?: number | string | Array<any>,
  pt?: number | string | Array<any>,
  px?: number | string | Array<any>,
  py?: number | string | Array<any>,
  height?: number | string | Array<any>,
  width?: number | string | Array<any>,
  fontSize?: number | string | Array<any>,
  bg?: number | string | Array<any>,
  color?: number | string | Array<any>,
  flex?: number | string | Array<any>,
  order?: number | string | Array<any>,
  alignSelf?: number | string | Array<any>,
  border?: number | string | Array<any>,
  borderBottom?: number | string | Array<any>,
  borderLeft?: number | string | Array<any>,
  borderRight?: number | string | Array<any>,
  borderTop?: number | string | Array<any>,
  borderColor?: number | string | Array<any>,
  borderRadius?: number | string | Array<any>,
  boxShadow?: number | string | Array<any>,
  maxWidth?: number | string | Array<any>,
  minWidth?: number | string | Array<any>,
  maxHeight?: number | string | Array<any>,
  minHeight?: number | string | Array<any>,
  display?: number | string | Array<any>,
  verticalAlign?: number | string | Array<any>,
  opacity?: number | string | Array<any>,
  overflow?: number | string | Array<any>,
  ratio?: number | string | Array<any>,
  flexBasis?: number | string | Array<any>,
  background?: number | string | Array<any>,
  backgroundImage?: number | string | Array<any>,
  backgroundSize?: number | string | Array<any>,
  backgroundPosition?: number | string | Array<any>,
  backgroundRepeat?: number | string | Array<any>,
  position?: number | string | Array<any>,
  zIndex?: number | string | Array<any>,
  left?: number | string | Array<any>,
  top?: number | string | Array<any>,
  right?: number | string | Array<any>,
  bottom?: number | string | Array<any>,
  // Additional props
  flexWrap?: number | string | Array<any>,
  flexDirection?: number | string | Array<any>,
  alignItems?: number | string | Array<any>,
  alignContent?: number | string | Array<any>,
  justifyContent?: number | string | Array<any>
}

declare const StyledFlex: SFC<StyledFlexProps>;

export default StyledFlex;
