import React from 'react';
import { Pagination } from './Pagination';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Pagination,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=5047-695',
  {
    props: {
      showMenu: figma.boolean('Show menu'),
      type: figma.enum('Type', {
        Default: 'default',
        Compact: 'compact'
      }),
      menu: figma.enum('Menu', {
        Open: 'open',
        Closed: 'closed'
      })
    },
    example: (props) => <Pagination />
  }
);

figma.connect(
  Pagination,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=4917-3142',
  {
    props: {
      total: figma.string('Total '),
      type: figma.enum('Type', {
        Default: 'default',
        Compact: 'compact'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Disabled: 'disabled'
      })
    },
    example: (props) => <Pagination />
  }
);

figma.connect(
  Pagination,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=4917-4769',
  {
    props: {
      totalQuantity: figma.string('Total quantity'),
      pageQuantity: figma.string('Page quantity'),
      state: figma.enum('State', {
        Default: 'default',
        Disabled: 'disabled',
        Hover: 'hover',
        Expanded: 'expanded'
      })
    },
    example: (props) => <Pagination />
  }
);
