import React from "react"
import { DualListItemTypes } from "./DualListItemTypes"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DualListItemTypes,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=21279-116327&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      type: figma.enum("Type", {
        Default: "default",
        "Expandable - collapsed": "expandable---collapsed",
        "Expandable - open": "expandable---open",
        "Sub item": "sub-item",
        "Sub item - Expandable - Closed": "sub-item---expandable---closed",
        "Sub item - Expandable - Open": "sub-item---expandable---open",
      }),
    },
    example: (props) => <DualListItemTypes />,
  },
)
