import React from "react"
import { DualListHeader } from "./DualListHeader"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DualListHeader,
  "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=21279-116172&t=IzSunfrnw18ti37Y-11",
  {
    props: {
      itemInformation: figma.string("Item information"),
      headerText: figma.string("Header text"),
      hasSearchBar: figma.boolean("Has search bar"),
    },
    example: (props) => <DualListHeader />,
  },
)
