import React from 'react';
import { BackToTop } from './BackToTop';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BackToTop,
  'https://www.figma.com/design/YqvMyyV4G347jSOgfYXi29/test-code-connect?node-id=1521-958&m=dev',
  {
    props: {
      title: figma.string('Text')
    },
    example: ({ title }) => <BackToTop title={title} />
  }
);
