import figma from '@figma/code-connect';
import { NavItem } from '@patternfly/react-core';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  NavItem,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/PatternFly-6--Components?node-id=2104-7269&m=dev',
  {
    props: {
      isActive: figma.enum('State', { Selected: true }),
      navItemText: figma.string('Nav item')
    },
    example: (props) => (
      <NavItem preventDefault id="<target-link-id>" itemId="<link-id>" to="#<target-link-id>" isActive={props.isActive}>
        {props.navItemText}
      </NavItem>
    )
  }
);
