// import React from "react"
// import { _1BuildItYourselfDraggableRows } from "./_1BuildItYourselfDraggableRows"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   _1BuildItYourselfDraggableRows,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=19618-55289&m=dev",
//   {
//     props: {
//       showRightActions: figma.boolean("Show right actions"),
//       showLeftControls: figma.boolean("Show Left controls"),
//       size: figma.enum("Size", {
//         Default: "default",
//         Compact: "compact",
//       }),
//       state: figma.enum("State", {
//         Default: "default",
//         "On Drag": "on-drag",
//         "Drag Outside": "drag-outside",
//       }),
//       selected: figma.boolean("Selected"),
//       expanded: figma.enum("Expanded", {
//         False: "false",
//       }),
//     },
//     example: (props) => <_1BuildItYourselfDraggableRows />,
//   },
// )
