// import React from "react"
// import { _1BuildItYourselfBasicRows } from "./_1BuildItYourselfBasicRows"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   _1BuildItYourselfBasicRows,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=6649-69488&m=dev",
//   {
//     props: {
//       showRightActions: figma.boolean("Show right actions"),
//       showLeftControls: figma.boolean("Show Left controls"),
//       size: figma.enum("Size", {
//         Default: "default",
//         Compact: "compact",
//       }),
//       selected: figma.boolean("Selected"),
//       expanded: figma.boolean("Expanded"),
//     },
//     example: (props) => <_1BuildItYourselfBasicRows />,
//   },
// )
