// import React from "react"
// import { _2BaseComponentsActionCell } from "./_2BaseComponentsActionCell"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   _2BaseComponentsActionCell,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=6596-33965&m=dev",
//   {
//     props: {
//       showLinkButton: figma.boolean("Show Link Button"),
//       showIconButton: figma.boolean("Show Icon Button"),
//       showButton: figma.boolean("Show Button"),
//       size: figma.enum("Size", {
//         Default: "default",
//         Compact: "compact",
//       }),
//     },
//     example: (props) => <_2BaseComponentsActionCell />,
//   },
// )
