// import React from "react"
// import { _2BaseComponentsContentCell } from "./_2BaseComponentsContentCell"
// import figma from "@figma/code-connect"

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(
//   _2BaseComponentsContentCell,
//   "https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=6596-33934&m=dev",
//   {
//     props: {
//       showFirstRow: figma.boolean("Show first row"),
//       showEmptyComponent: figma.boolean("Show empty component"),
//       emptyComponentSwap: figma.instance("Empty component swap"),
//       showDescriptionText: figma.boolean("Show description text"),
//       showSecondRow: figma.boolean("Show second row"),
//       showIcon: figma.boolean("Show Icon"),
//       type: figma.enum("Type", {
//         "Filled - Plain text": "filled---plain-text",
//         "Filled - Link text": "filled---link-text",
//         "Empty (Component swap)": "empty--component-swap-",
//       }),
//       size: figma.enum("Size", {
//         Default: "default",
//         Compact: "compact",
//       }),
//     },
//     example: (props) => <_2BaseComponentsContentCell />,
//   },
// )
