import React from 'react';
import { Page } from './Page';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Page,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=25656-311494',
  {
    props: {
      type: figma.enum('type', {
        'simple list': 'simple-list',
        'with drawer': 'with-drawer',
        'with inline drawer': 'with-inline-drawer',
        'data list': 'data-list'
      })
    },
    example: (props) => <Page />
  }
);

figma.connect(
  Page,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=25656-311374',
  {
    props: {
      type: figma.enum('Type', {
        Primary: 'primary',
        Mixed: 'mixed',
        'All secondary': 'all-secondary',
        DIY: 'diy'
      })
    },
    example: (props) => <Page />
  }
);

figma.connect(
  Page,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=25656-311411',
  {
    props: {},
    example: (props) => <Page />
  }
);

figma.connect(
  Page,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=25656-311437',
  {
    props: {},
    example: (props) => <Page />
  }
);

figma.connect(
  Page,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=25656-311394',
  {
    props: {},
    example: (props) => <Page />
  }
);

figma.connect(
  Page,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=7620-35193',
  {
    props: {
      contentAreaPresets: figma.instance('Content area presets'),
      navPlacement: figma.enum('Nav Placement', {
        Masthead: 'masthead',
        'In page': 'in-page'
      })
    },
    example: (props) => <Page />
  }
);

figma.connect(
  Page,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=3864-23403',
  {
    props: {
      contentAreaPresets: figma.instance('Content Area Presets'),
      sideNav: figma.enum('Side nav', {
        Open: 'open',
        Closed: 'closed'
      })
    },
    example: (props) => <Page />
  }
);
