import fs from 'fs/promises';
import path from 'path';
import getIconConfig from '../utils/config.mjs';

// Get the configuration
const config = getIconConfig();
const { logger } = config;

/**
 * Extract icon names from import statement
 * @param {string} importStatement - The full import statement
 * @returns {string[]} Array of unique icon names
 */
function extractIconNames(importStatement) {
  // Remove comments and extra whitespace
  const cleanImport = importStatement
    .replace(/\/\/.*|\/\*[\s\S]*?\*\//g, '')
    .replace(/\s+/g, ' ')
    .trim();

  // Extract icons between { }
  const matchIcons = cleanImport.match(/{\s*(.+?)\s*}/);

  if (!matchIcons) {
    return [];
  }

  // Split icons and clean up
  return [
    ...new Set(
      matchIcons[1]
        .split(',')
        .map((icon) => icon.trim())
        .filter((icon) => icon && !icon.includes('=') && !icon.startsWith('Icon Size') && !icon.includes('('))
    )
  ];
}

/**
 * Generate Figma connections for icons
 */
async function generateIconConnections() {
  try {
    // Read the existing icons data
    const iconsDataPath = config.iconsDataPath;
    let iconsData = [];

    try {
      const iconsDataContent = await fs.readFile(iconsDataPath, 'utf8');
      iconsData = JSON.parse(iconsDataContent);
    } catch (error) {
      logger.warn('Could not read icons data, using minimal configuration', {
        source: 'IconConnectionGenerator',
        context: { path: iconsDataPath, error: error.message }
      });
    }

    // Resolve the output file path using existing configuration
    const connectionFilePath = path.resolve(config.iconsFigmaDir, config.figmaOutputFile);
    console.log(connectionFilePath);

    // Read the current icon connection file
    const existingContent = await fs.readFile(connectionFilePath, 'utf8').catch(
      () => `
import {
  AddCircleOIcon, AngleDoubleLeftIcon, AngleDoubleRightIcon, AngleDownIcon
} from "./generated";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by the figmaConnector script --
 * This file connects icon components to their corresponding Figma components.
 */
`
    );

    // Extract unique icon names
    const uniqueIconNames = extractIconNames(existingContent);

    // Generate import statement
    const importStatement = `import {
  ${uniqueIconNames.join(', ')}
} from "./@patternfly/react-icons";`;

    // Generate connection content
    const connectionContent = `
${importStatement}
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by the figmaConnector script --
 * This file connects icon components to their corresponding Figma components.
 */

${uniqueIconNames
  .map((iconName) => {
    // Try to find a matching icon in iconsData
    const iconConfig = iconsData.find(
      (icon) =>
        icon.reactName === iconName || icon.fileName.replace('-icon', '') === iconName.replace('Icon', '').toLowerCase()
    );

    // Use the URL directly from iconsData if available
    const url = iconConfig?.url || `${config.figmaBaseUrl}?node-id=${config.defaultNodeId}&m=dev`;

    // Use a more compact format for figma.connect()
    return `figma.connect(${iconName}, "${url}", {
  props: {},
  example: (props) => <${iconName} {...props} />
});`;
  })
  .join('\n\n')}
`;

    // Write the updated connection file
    await fs.writeFile(connectionFilePath, connectionContent, 'utf8');

    logger.success('Generated icon connections', {
      source: 'IconConnectionGenerator',
      context: {
        uniqueIconCount: uniqueIconNames.length,
        outputPath: connectionFilePath
      }
    });

    return true;
  } catch (error) {
    logger.error('Error generating icon connections', error, {
      source: 'IconConnectionGenerator'
    });
    return false;
  }
}

// Run the script
generateIconConnections()
  .then((success) => process.exit(success ? 0 : 1))
  .catch(() => process.exit(1));
