/* eslint-disable no-console */
import fs from 'fs/promises';
import getIconConfig from '../utils/config.mjs';
import path from 'path';
import { existsSync } from 'fs';

/**
 * Extract node ID from URL
 * @param {string} url - Figma URL
 * @returns {string|null} - Node ID or null if not found
 */
function extractNodeId(url) {
  if (!url) {
    return null;
  }
  const nodeIdMatch = url.match(/node-id=([^&]+)/);
  return nodeIdMatch ? nodeIdMatch[1] : null;
}

/**
 * Generate individual icon files and Figma connections
 */
async function generateIcons() {
  // Get configuration
  const config = getIconConfig();
  const { logger } = config;

  try {
    // Ensure output directories exist
    await fs.mkdir(config.iconsGeneratedDir, { recursive: true });
    await fs.mkdir(config.iconsFigmaDir, { recursive: true });

    // Read icon template
    let iconTemplate = '';
    try {
      iconTemplate = await fs.readFile(config.iconTemplatePath, 'utf8');
      logger.success(`Loaded icon template from ${config.iconTemplatePath}`);
    } catch (readTemplateError) {
      logger.error('Failed to read icon template', readTemplateError);
      throw readTemplateError;
    }

    // Read icon data
    let iconData = [];
    try {
      const iconsDataJson = await fs.readFile(config.iconsDataPath, 'utf8');
      iconData = JSON.parse(iconsDataJson);
      logger.success(`Loaded ${iconData.length} icons from ${config.iconsDataPath}`);
    } catch (readDataError) {
      logger.error('Failed to read icons data', readDataError);

      // Provide example data if file is missing
      iconData = [
        {
          iconName: 'angle-down',
          fileName: 'angle-down-icon',
          reactName: 'AngleDownIcon',
          url: `${config.figmaBaseUrl}?node-id=${config.defaultNodeId}&m=dev`,
          svgPath: '<path d="M12 15.5l-6-6 1.4-1.4 4.6 4.6 4.6-4.6 1.4 1.4z" />'
        }
      ];
      logger.warn('Using example icon data');
    }

    // Ensure iconData is an array to avoid TypeError
    if (!Array.isArray(iconData)) {
      logger.warn('iconData is not an array, initializing as empty array');
      iconData = [];
    }

    // Check and log node ID coverage
    const iconsWithNodeIds = iconData.filter((icon) => icon.url && extractNodeId(icon.url));
    logger.info(`Found node IDs for ${iconsWithNodeIds.length} of ${iconData.length} icons`);

    // Generate individual icon files
    const iconGenerationPromises = iconData.map(async (icon) => {
      // Use safe defaults for all properties to avoid undefined errors
      const iconFileName = icon && icon.fileName ? icon.fileName : 'default-icon';

      // Use the template and replace placeholders with safe defaults
      const iconContent = iconTemplate
        .replace('ICON_NAME', icon && icon.reactName ? icon.reactName : 'DefaultIcon')
        .replace(
          'SVG_PATH',
          icon && icon.svgPath
            ? icon.svgPath
            : '<path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2z" />'
        );

      const iconPath = path.join(config.iconsGeneratedDir, `${iconFileName}.tsx`);
      await fs.writeFile(iconPath, iconContent);
      return icon;
    });

    const generatedIcons = await Promise.all(iconGenerationPromises);
    logger.success(`Generated ${generatedIcons.length} individual icon files`);

    // Create IconProps.ts if it doesn't exist
    const iconPropsPath = path.join(path.dirname(config.iconsGeneratedDir), 'IconProps.ts');
    if (!existsSync(iconPropsPath)) {
      const iconPropsContent = `import { SVGProps } from 'react';

export interface IconProps extends SVGProps<SVGSVGElement> {
  /** Additional classes added to the icon */
  className?: string;
  /** Icon title for accessibility */
  title?: string;
}
`;
      await fs.writeFile(iconPropsPath, iconPropsContent);
      logger.success(`Created IconProps.ts file at ${iconPropsPath}`);
    }

    // Generate Figma connection file
    const componentNames = generatedIcons
      .filter((icon) => icon && icon.reactName) // Filter out any undefined values
      .map((icon) => icon.reactName)
      .sort();

    // Generate Figma connection file with node IDs
    const figmaFileContent = `import React from "react";
import figma from "@figma/code-connect";
import { ${componentNames.join(', ')} } from "./generated";

/**
 * -- This file was auto-generated by the icon generator script --
 * This file connects icon components to their corresponding Figma components.
 */

${generatedIcons
  .filter((icon) => icon && icon.reactName) // Filter out any icons without a reactName
  .map((icon) => {
    // Extract node ID from URL or use default
    const nodeId = icon.url ? extractNodeId(icon.url) || config.defaultNodeId : config.defaultNodeId;

    const url = `${config.figmaBaseUrl}?node-id=${nodeId}&m=dev`;

    return `figma.connect(
  ${icon.reactName},
  "${url}",
  {
    props: {},
    example: (props) => <${icon.reactName} {...props} />
  }
);`;
  })
  .join('\n\n')}
`;

    // Write Figma connection file
    const figmaOutputPath = path.join(config.iconsFigmaDir, config.figmaOutputFile);
    await fs.writeFile(figmaOutputPath, figmaFileContent);
    logger.success(`Generated Figma connection file at ${figmaOutputPath}`);

    // Generate index file for generated icons
    const indexContent = generatedIcons
      .filter((icon) => icon && icon.reactName && icon.fileName) // Filter out any undefined values
      .map((icon) => `export { ${icon.reactName} } from './${icon.fileName}';`)
      .join('\n');

    const indexPath = path.join(config.iconsGeneratedDir, config.generatedIndexFile);
    await fs.writeFile(indexPath, indexContent);
    logger.success(`Generated index file at ${indexPath}`);

    return true;
  } catch (error) {
    // Ensure error is logged with full details
    console.error('Detailed error in generateIcons:', error);

    // If logger exists, use it
    if (config.logger && typeof config.logger.error === 'function') {
      config.logger.error('Error generating icon files', error);
    } else {
      // Fallback logging if logger is undefined
      console.error('Error generating icon files:', error);
    }

    return false;
  }
}

/**
 * Main function to run the icon generation process
 */
async function main() {
  const config = getIconConfig();
  const { logger } = config;

  const args = process.argv.slice(2);

  // Handle custom input path if provided
  const inputPathIndex = args.indexOf('--input');
  if (inputPathIndex !== -1 && args.length > inputPathIndex + 1) {
    config.iconsDataPath = args[inputPathIndex + 1];
    logger.info(`Using custom input path: ${config.iconsDataPath}`);
  }

  // Generate icons
  const success = await generateIcons();

  if (success) {
    logger.success('Icon generation completed successfully! 🎉');
    console.log('To publish to Figma, run:');
    console.log('  cd react-core');
    console.log('  npx figma connect publish --token=your_token');
    process.exit(0);
  } else {
    logger.error('Failed to generate icon files');
    process.exit(1);
  }
}

// Run the script
main().catch((error) => {
  console.error('Unhandled error in main:', error);
  process.exit(1);
});
