import React from 'react';
import { CodeBlock } from './CodeBlock';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CodeBlock,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=9802-5857',
  {
    props: {
      action4: figma.boolean('Action 4'),
      expandable: figma.boolean('Expandable'),
      action3: figma.boolean('Action 3'),
      action5: figma.boolean('Action 5'),
      action2: figma.boolean('Action 2'),
      action1: figma.boolean('Action 1'),
      property1: figma.enum('Property 1', {
        Default: 'default'
      })
    },
    example: (props) => <CodeBlock />
  }
);
