import React from 'react';
import { Badge } from './Badge';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(Badge, 'https://www.figma.com/design/YqvMyyV4G347jSOgfYXi29/test-code-connect?node-id=1259-1132&m=dev', {
  props: {
    text: figma.string('Text'),
    isDisabled: figma.enum('Type', { disabled: true }),
    isRead: figma.enum('Type', { Read: true }),
    screenReaderText: figma.enum('Type', { Unread: 'Unread Messages' })
  },
  example: ({ text, ...props }) => <Badge {...props}>{text}</Badge>
});
