import React from 'react';
import { Tab } from './Tab';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14327-6407',
  {
    props: {
      helpIcon: figma.boolean('Help icon'),
      closeIcon: figma.boolean('Close Icon'),
      hasIcon: figma.boolean('Has icon'),
      text: figma.string('Text'),
      type: figma.enum('Type', {
        'Default tab': 'default-tab',
        'Box tab': 'box-tab',
        'Last Brd Rght': 'last-brd-rght',
        'First/Last Left Border': 'first-last-left-border',
        'First/Last Right Border': 'first-last-right-border',
        'Boxed light': 'boxed-light'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        Disabled: 'disabled'
      })
    },
    example: (props) => <Tab />
  }
);

figma.connect(
  Tab,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14327-6583',
  {
    props: {
      inset: figma.boolean('Inset'),
      type: figma.enum('Type', {
        Default: 'default',
        Boxed: 'boxed',
        'Boxed Light': 'boxed-light',
        'Horizontal overflow': 'horizontal-overflow',
        'With overflow': 'with-overflow'
      })
    },
    example: (props) => <Tab />
  }
);

figma.connect(
  Tab,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14327-6503',
  {
    props: {
      showRightScrollArrow: figma.boolean('Show Right Scroll Arrow'),
      showLeftScrollArrow: figma.boolean('Show Left Scroll Arrow'),
      inset: figma.boolean('Inset'),
      type: figma.enum('Type', {
        Default: 'default',
        Boxed: 'boxed',
        'Boxed Light': 'boxed-light',
        'With overflow': 'with-overflow',
        'With horizontal overflow': 'with-horizontal-overflow',
        Dynamic: 'dynamic'
      })
    },
    example: (props) => <Tab />
  }
);

figma.connect(
  Tab,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14327-6161',
  {
    props: {
      moreTabText: figma.string('More Tab Text'),
      closeButton: figma.boolean('Close button'),
      helpButton: figma.boolean('Help button'),
      hasIcon: figma.boolean('Has icon'),
      tabText: figma.string('Tab Text'),
      type: figma.enum('Type', {
        'Default tab': 'default-tab',
        'Box tab': 'box-tab',
        'Boxed Light': 'boxed-light',
        Inset: 'inset',
        'Inset Boxed': 'inset-boxed',
        More: 'more'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        Disabled: 'disabled'
      })
    },
    example: (props) => <Tab />
  }
);

figma.connect(
  Tab,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14327-6284',
  {
    props: {
      moreTabText: figma.string('More Tab Text'),
      closeIcon: figma.boolean('Close Icon'),
      helpIcon: figma.boolean('Help icon'),
      hasIcon: figma.boolean('Has icon'),
      tabText: figma.string('Tab Text'),
      type: figma.enum('Type', {
        'Default tab': 'default-tab',
        'Box tab': 'box-tab',
        Inset: 'inset',
        'Inset Boxed': 'inset-boxed',
        More: 'more',
        'Boxed Light': 'boxed-light'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        Disabled: 'disabled'
      })
    },
    example: (props) => <Tab />
  }
);

figma.connect(
  Tab,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14327-6407',
  {
    props: {
      helpIcon: figma.boolean('Help icon'),
      closeIcon: figma.boolean('Close Icon'),
      hasIcon: figma.boolean('Has icon'),
      text: figma.string('Text'),
      type: figma.enum('Type', {
        'Default tab': 'default-tab',
        'Box tab': 'box-tab',
        'Last Brd Rght': 'last-brd-rght',
        'First/Last Left Border': 'first-last-left-border',
        'First/Last Right Border': 'first-last-right-border',
        'Boxed light': 'boxed-light'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        Disabled: 'disabled'
      })
    },
    example: (props) => <Tab />
  }
);

figma.connect(
  Tab,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14327-6656',
  {
    props: {
      type: figma.enum('Type', {
        Default: 'default',
        Boxed: 'boxed',
        'Boxed Light': 'boxed-light',
        Expandable: 'expandable'
      })
    },
    example: (props) => <Tab />
  }
);
