import React from 'react';
import { Toolbar } from './Toolbar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Toolbar,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=8062-17157',
  {
    props: {
      filterGroup: figma.boolean('Filter group'),
      linkButtons: figma.boolean('Link buttons'),
      pagination: figma.boolean('Pagination'),
      verticalDivider: figma.boolean('Vertical divider'),
      searchFilter: figma.boolean('Search filter'),
      bulkSelector: figma.boolean('Bulk Selector'),
      buttonGroup: figma.boolean('Button group'),
      filterChips: figma.boolean('Filter chips'),
      iconButtonGroup: figma.boolean('Icon button group'),
      overflowMenu: figma.boolean('Overflow menu'),
      transparentBackground: figma.boolean('Transparent Background')
    },
    example: (props) => <Toolbar />
  }
);
