import React from 'react';
import { Accordion } from './Accordion';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Accordion,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2621-623',
  {
    props: {
      type: figma.enum('Type', {
        Default: 'default',
        Bordered: 'bordered'
      }),
      caretPosition: figma.enum('Caret position', {
        Right: 'right',
        Left: 'left'
      })
    },
    example: (props) => <Accordion type={props.type}>test</Accordion>
  }
);

figma.connect(
  Accordion,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2621-623',
  {
    props: {
      // toggleTextLarge: figma.string("Toggle Text Large"),
      // toggleTextExpanded: figma.string("Toggle Text Expanded"),
      // toggleText: figma.string("Toggle Text"),
      // expandText: figma.string("Expand Text"),
      type: figma.enum("Type", {
        Regular: "regular",
        Bordered: "bordered",
        "Large Bordered": "large-bordered",
      }),
      // state: figma.enum("State", {
      //   Default: "default",
      //   Hover: "hover",
      //   Expanded: "expanded",
      // }),
      caretPosition: figma.enum("Caret position", {
        Right: "right",
        Left: "left",
      }),
    },
    example: (props) => <Accordion>check me out</Accordion>,
  },
)
