// import React from 'react';
// import { AboutModal } from './AboutModal';
// import figma from '@figma/code-connect';

// /**
//  * -- This file was auto-generated by Code Connect --
//  * `props` includes a mapping from Figma properties and variants to
//  * suggested values. You should update this to match the props of your
//  * code component, and update the `example` function to return the
//  * code example you'd like to see in Figma
//  */

// figma.connect(AboutModal, '[object Object]2879-13973', {
//   props: {
//     productName: figma.string('Product name')
//   },
//   example: (props) => <AboutModal />
// });
