import React from 'react';
import { Avatar } from 'src/components/Avatar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=1561-4342',
  {
    props: {
      isBordered: figma.boolean('Bordered'),
      size: figma.enum('Size', {
        small: 'sm',
        med: 'md',
        lg: 'lg',
        XL: 'xl'
      })
    },
    example: (props) => <Avatar alt="avatar" {...props} />
  }
);
