import React from 'react';
import { BackgroundImage } from 'src/components/BackgroundImage';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  BackgroundImage,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?node-id=2722-13543&t=7hKW0DzmfHGhNQnn-11',
  {
    props: {
      theme: figma.enum('Theme', {
        'On Primary': 'on-primary',
        'On Secondary': 'on-secondary'
      })
    },
    example: (props) => <BackgroundImage />
  }
);
