import React from 'react';
import { Checkbox } from 'src/components/Checkbox';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Checkbox,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=157-1280',
  {
    props: {
      isChecked: figma.enum('State', {
        Unchecked: false,
        Checked: true,
        // TODO:  Figma doesn't support null values, so we'll need to figure out a way to represent this
        // Mixed: null,
        'Unchecked Disabled': false,
        'Checked Disabled': true
        // TODO:  Figma doesn't support null values, so we'll need to figure out a way to represent this
        // 'Mixed disabled': null
      }),
      isDisabled: figma.enum('State', {
        'Unchecked Disabled': true,
        'Checked Disabled': true,
        'Mixed disabled': true
      })
    },
    example: (props) => <Checkbox id="checkbox-id" {...props} />
  }
);
