import React from 'react';
import { DataList } from 'src/components/DataList';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DataList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=6649-80542',
  {
    props: {
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      }),
      type: figma.enum('Type', {
        Basic: 'basic',
        Selectable: 'selectable',
        'Clickable + Selectable': 'clickable---selectable',
        Clickable: 'clickable'
      }),
      expandable: figma.boolean('Expandable')
    },
    example: (props) => <DataList />
  }
);

figma.connect(
  DataList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=6649-69488',
  {
    props: {
      showRightActions: figma.boolean('Show right actions'),
      showLeftControls: figma.boolean('Show Left controls'),
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      }),
      selected: figma.boolean('Selected'),
      expanded: figma.boolean('Expanded')
    },
    example: (props) => <_1BuildItYourselfBasicRows />
  }
);

figma.connect(
  DataList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=6649-96947',
  {
    props: {
      showRightActions: figma.boolean('Show right actions'),
      showLeftControls: figma.boolean('Show Left controls'),
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Clicked: 'clicked'
      }),
      selected: figma.boolean('Selected'),
      expanded: figma.boolean('Expanded')
    },
    example: (props) => <_1BuildItYourselfClickableRows />
  }
);

figma.connect(
  DataList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=19618-55289',
  {
    props: {
      showRightActions: figma.boolean('Show right actions'),
      showLeftControls: figma.boolean('Show Left controls'),
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      }),
      state: figma.enum('State', {
        Default: 'default',
        'On Drag': 'on-drag',
        'Drag Outside': 'drag-outside'
      }),
      selected: figma.boolean('Selected'),
      expanded: figma.enum('Expanded', {
        False: 'false'
      })
    },
    example: (props) => <_1BuildItYourselfDraggableRows />
  }
);

figma.connect(
  DataList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=6596-33965',
  {
    props: {
      showLinkButton: figma.boolean('Show Link Button'),
      showIconButton: figma.boolean('Show Icon Button'),
      showButton: figma.boolean('Show Button'),
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      })
    },
    example: (props) => <_2BaseComponentsActionCell />
  }
);

figma.connect(
  DataList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=6596-33934',
  {
    props: {
      showFirstRow: figma.boolean('Show first row'),
      showEmptyComponent: figma.boolean('Show empty component'),
      emptyComponentSwap: figma.instance('Empty component swap'),
      showDescriptionText: figma.boolean('Show description text'),
      showSecondRow: figma.boolean('Show second row'),
      showIcon: figma.boolean('Show Icon'),
      type: figma.enum('Type', {
        'Filled - Plain text': 'filled---plain-text',
        'Filled - Link text': 'filled---link-text',
        'Empty (Component swap)': 'empty--component-swap-'
      }),
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      })
    },
    example: (props) => <_2BaseComponentsContentCell />
  }
);

figma.connect(
  DataList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=6596-34013',
  {
    props: {
      rowExpansion: figma.boolean('Row expansion'),
      isDraggable: figma.boolean('Is Draggable'),
      rowSelect: figma.boolean('Row select'),
      size: figma.enum('Size', {
        Default: 'default',
        Compact: 'compact'
      })
    },
    example: (props) => <DataList />
  }
);
