import React from "react"
import { Hint } from "src/components/Hint"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Hint,
  "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=1118-3329",
  {
    props: {
      showFooter: figma.boolean("Show Footer"),
      body: figma.string("✏️ Body"),
      title: figma.string("✏️ Title"),
      swapButton: figma.instance("Swap button"),
      showBody: figma.boolean("Show Body"),
      showTitle: figma.boolean("Show Title "),
    },
    example: (props) => <Hint />,
  },
)
