import React from "react";
import { Icon } from "src/components/Icon";
import figma from "@figma/code-connect";

// Import all icons from an index file
import * as Icons from '../icons';

/**
 * -- This file connects the Icon component to Figma --
 * Uses instance swapper to allow selecting different icons
 */

figma.connect(
  Icon,
  "https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=198-1573",
  {
    props: {
      icon: figma.instance("🖼️ Icon", {
        // START_ICON_INSTANCES
        'up-right-and-down-left-from-center-solid': <Icons.UprightanddownleftfromcentersolidIcon />,
        'cogs': <Icons.CogsIcon />,
        'not-started': <Icons.NotstartedIcon />,
        'angle-right': <Icons.AnglerightIcon />,
        'search': <Icons.SearchIcon />,
        'angle-double-left': <Icons.AngledoubleleftIcon />,
        'trend-up': <Icons.TrendupIcon />,
        'arrow-right': <Icons.ArrowrightIcon />,
        'down-left-and-up-right-to-center-solid': <Icons.DownleftanduprighttocentersolidIcon />,
        'github': <Icons.GithubIcon />,
        'exclamation-triangle': <Icons.ExclamationtriangleIcon />,
        'cubes': <Icons.CubesIcon />,
        'search': <Icons.SearchIcon />,
        'linkedin': <Icons.LinkedinIcon />,
        'plus-circle': <Icons.PluscircleIcon />,
        'check-circle': <Icons.CheckcircleIcon />,
        'wrench': <Icons.WrenchIcon />,
        'twitter': <Icons.TwitterIcon />,
        'history': <Icons.HistoryIcon />,
        'bars': <Icons.BarsIcon />,
        'wrench': <Icons.WrenchIcon />,
        'balance-scale': <Icons.BalancescaleIcon />,
        'thumbtack': <Icons.ThumbtackIcon />,
        'cloud-tenant': <Icons.CloudtenantIcon />,
        'panel-open': <Icons.PanelopenIcon />,
        'add-circle-o': <Icons.AddcircleoIcon />,
        'dropbox': <Icons.DropboxIcon />,
        'redo': <Icons.RedoIcon />,
        'data-processor': <Icons.DataprocessorIcon />,
        'resources-almost-empty': <Icons.ResourcesalmostemptyIcon />,
        'drupal': <Icons.DrupalIcon />,
        'middleware': <Icons.MiddlewareIcon />,
        'cluster': <Icons.ClusterIcon />,
        'cog': <Icons.CogIcon />,
        'pencil-alt': <Icons.PencilaltIcon />,
        'th-large': <Icons.ThlargeIcon />,
        'new-process': <Icons.NewprocessIcon />,
        'long-arrow-alt-up': <Icons.LongarrowaltupIcon />,
        'automation': <Icons.AutomationIcon />,
        'openstack': <Icons.OpenstackIcon />,
        'connected': <Icons.ConnectedIcon />,
        'pause-circle': <Icons.PausecircleIcon />,
        'share-square': <Icons.SharesquareIcon />,
        'check': <Icons.CheckIcon />,
        'database': <Icons.DatabaseIcon />,
        'sort-amount-down-alt': <Icons.SortamountdownaltIcon />,
        'panel-close': <Icons.PanelcloseIcon />,
        'satellite': <Icons.SatelliteIcon />,
        'clipboard-check': <Icons.ClipboardcheckIcon />,
        'severity-moderate': <Icons.SeveritymoderateIcon />,
        'folder': <Icons.FolderIcon />,
        'sort-amount-down': <Icons.SortamountdownIcon />,
        'catalog': <Icons.CatalogIcon />,
        'calendar': <Icons.CalendarIcon />,
        'eye': <Icons.EyeIcon />,
        'pause': <Icons.PauseIcon />,
        'enhancement': <Icons.EnhancementIcon />,
        'expand-arrows-alt': <Icons.ExpandarrowsaltIcon />,
        'code-branch': <Icons.CodebranchIcon />,
        'resource-pool': <Icons.ResourcepoolIcon />,
        'times': <Icons.TimesIcon />,
        'cloud-security': <Icons.CloudsecurityIcon />,
        'question-circle': <Icons.QuestioncircleIcon />,
        'network-range': <Icons.NetworkrangeIcon />,
        'off': <Icons.OffIcon />,
        'resources-full': <Icons.ResourcesfullIcon />,
        'play': <Icons.PlayIcon />,
        'window-restore': <Icons.WindowrestoreIcon />,
        'severity-minor': <Icons.SeverityminorIcon />,
        'undo': <Icons.UndoIcon />,
        'task': <Icons.TaskIcon />,
        'arrow-circle-down': <Icons.ArrowcircledownIcon />,
        'template': <Icons.TemplateIcon />,
        'print': <Icons.PrintIcon />,
        'tenant': <Icons.TenantIcon />,
        'arrow-circle-up': <Icons.ArrowcircleupIcon />,
        'monitoring': <Icons.MonitoringIcon />,
        'disconnected': <Icons.DisconnectedIcon />,
        'regions': <Icons.RegionsIcon />,
        'ban': <Icons.BanIcon />,
        'search-minus': <Icons.SearchminusIcon />,
        'unknown': <Icons.UnknownIcon />,
        'data-source': <Icons.DatasourceIcon />,
        'bundle': <Icons.BundleIcon />,
        'check-circle': <Icons.CheckcircleIcon />,
        'stack-overflow': <Icons.StackoverflowIcon />,
        'network': <Icons.NetworkIcon />,
        'download': <Icons.DownloadIcon />,
        'storage-domain': <Icons.StoragedomainIcon />,
        'severity-unidentified': <Icons.SeverityunidentifiedIcon />,
        'user': <Icons.UserIcon />,
        'severity-none': <Icons.SeveritynoneIcon />,
        'filter': <Icons.FilterIcon />,
        'map-marker': <Icons.MapmarkerIcon />,
        'cube': <Icons.CubeIcon />,
        'volume': <Icons.VolumeIcon />,
        'server-group': <Icons.ServergroupIcon />,
        'windows': <Icons.WindowsIcon />,
        'flavor': <Icons.FlavorIcon />,
        'ansible': <Icons.AnsibleIcon />,
        'user': <Icons.UserIcon />,
        'times-circle': <Icons.TimescircleIcon />,
        'memory': <Icons.MemoryIcon />,
        'star': <Icons.StarIcon />,
        'copy': <Icons.CopyIcon />,
        'arrows-alt-v': <Icons.ArrowsaltvIcon />,
        'table': <Icons.TableIcon />,
        'folder-open': <Icons.FolderopenIcon />,
        'arrow-right': <Icons.ArrowrightIcon />,
        'lock': <Icons.LockIcon />,
        'vcenter': <Icons.VcenterIcon />,
        'flag': <Icons.FlagIcon />,
        'list': <Icons.ListIcon />,
        'pause-circle': <Icons.PausecircleIcon />,
        'multicluster': <Icons.MulticlusterIcon />,
        'plus-circle': <Icons.PluscircleIcon />,
        'degraded': <Icons.DegradedIcon />,
        'cubes': <Icons.CubesIcon />,
        'pending': <Icons.PendingIcon />,
        'zone': <Icons.ZoneIcon />,
        'tag': <Icons.TagIcon />,
        'file': <Icons.FileIcon />,
        'service-catalog': <Icons.ServicecatalogIcon />,
        'tachometer-alt': <Icons.TachometeraltIcon />,
        'exclamation-circle': <Icons.ExclamationcircleIcon />,
        'treeview': <Icons.TreeviewIcon />,
        'comments': <Icons.CommentsIcon />,
        'enterprise': <Icons.EnterpriseIcon />,
        'resources-almost-full': <Icons.ResourcesalmostfullIcon />,
        'topology': <Icons.TopologyIcon />,
        'ellipsis-v': <Icons.EllipsisvIcon />,
        'image': <Icons.ImageIcon />,
        'desktop': <Icons.DesktopIcon />,
        'lock-open': <Icons.LockopenIcon />,
        'data-sink': <Icons.DatasinkIcon />,
        'service': <Icons.ServiceIcon />,
        'repository': <Icons.RepositoryIcon />,
        'builder-image': <Icons.BuilderimageIcon />,
        'code': <Icons.CodeIcon />,
        'process-automation': <Icons.ProcessautomationIcon />,
        'private': <Icons.PrivateIcon />,
        'domain': <Icons.DomainIcon />,
        'attention-bell': <Icons.AttentionbellIcon />,
        'in-progress': <Icons.InprogressIcon />,
        'key': <Icons.KeyIcon />,
        'running': <Icons.RunningIcon />,
        'minus-circle': <Icons.MinuscircleIcon />,
        'th': <Icons.ThIcon />,
        'services': <Icons.ServicesIcon />,
        'trend-down': <Icons.TrenddownIcon />,
        'user': <Icons.UserIcon />,
        'lock': <Icons.LockIcon />,
        'route': <Icons.RouteIcon />,
        'virtual-machine': <Icons.VirtualmachineIcon />,
        'linux': <Icons.LinuxIcon />,
        'registry': <Icons.RegistryIcon />,
        'home': <Icons.HomeIcon />,
        'power-off': <Icons.PoweroffIcon />,
        'open-drawer-right': <Icons.OpendrawerrightIcon />,
        'bug': <Icons.BugIcon />,
        'question-circle(far)': <Icons.QuestioncirclefarIcon />,
        'optimize': <Icons.OptimizeIcon />,
        'long-arrow-alt-down': <Icons.LongarrowaltdownIcon />,
        'minus': <Icons.MinusIcon />,
        'security': <Icons.SecurityIcon />,
        'port': <Icons.PortIcon />,
        'bell': <Icons.BellIcon />,
        'eye-slash': <Icons.EyeslashIcon />,
        'replicator': <Icons.ReplicatorIcon />,
        'infrastructure': <Icons.InfrastructureIcon />,
        'info-circle': <Icons.InfocircleIcon />,
        'hdd': <Icons.HddIcon />,
        'grip-vertical': <Icons.GripverticalIcon />,
        'angle-left': <Icons.AngleleftIcon />,
        'check': <Icons.CheckIcon />,
        'exclamation-triangle': <Icons.ExclamationtriangleIcon />,
        'grip-horizontal': <Icons.GriphorizontalIcon />,
        'angle-down': <Icons.AngledownIcon />,
        'bell': <Icons.BellIcon />,
        'compress': <Icons.CompressIcon />,
        'integration': <Icons.IntegrationIcon />,
        'clock': <Icons.ClockIcon />,
        'facebook': <Icons.FacebookIcon />,
        'asleep': <Icons.AsleepIcon />,
        'caret-down': <Icons.CaretdownIcon />,
        'exclamation-circle': <Icons.ExclamationcircleIcon />,
        'trash': <Icons.TrashIcon />,
        'expand': <Icons.ExpandIcon />,
        'sync-alt': <Icons.SyncaltIcon />,
        'compress-arrows-alt': <Icons.CompressarrowsaltIcon />,
        'export': <Icons.ExportIcon />,
        'blueprint': <Icons.BlueprintIcon />,
        'flag': <Icons.FlagIcon />,
        'save': <Icons.SaveIcon />,
        'upload': <Icons.UploadIcon />,
        'import': <Icons.ImportIcon />,
        'google': <Icons.GoogleIcon />,
        'resources-empty': <Icons.ResourcesemptyIcon />,
        'severity-critical': <Icons.SeveritycriticalIcon />,
        'openshift': <Icons.OpenshiftIcon />,
        'bitbucket': <Icons.BitbucketIcon />,
        'severity-important': <Icons.SeverityimportantIcon />,
        'cogs': <Icons.CogsIcon />,
        'gitlab': <Icons.GitlabIcon />,
        'columns': <Icons.ColumnsIcon />,
        'microchip': <Icons.MicrochipIcon />,
        'patternfly': <Icons.PatternflyIcon />,
        'search-plus': <Icons.SearchplusIcon />,
        'angle-double-right': <Icons.AngledoublerightIcon />,
        'build': <Icons.BuildIcon />,
        'check-circle-2xl': <Icons.Checkcircle2xlIcon />,
        'js': <Icons.JsIcon />,
        'angle-up': <Icons.AngleupIcon />,
        'plus': <Icons.PlusIcon />,
        'migration': <Icons.MigrationIcon />,
        'external-link-alt': <Icons.ExternallinkaltIcon />,
        'space-shuttle-2xl': <Icons.Spaceshuttle2xlIcon />,
        'thumbs-up-regular': <Icons.ThumbsupregularIcon />,
        'thumbs-down-regular': <Icons.ThumbsdownregularIcon />,
        'message': <Icons.MessageIcon />,
        'thumbs-up': <Icons.ThumbsupIcon />,
        'fingerprint': <Icons.FingerprintIcon />,
        'stop': <Icons.StopIcon />,
        'microphone': <Icons.MicrophoneIcon />,
        'volume-high': <Icons.VolumehighIcon />,
        'paperclip': <Icons.PaperclipIcon />,
        'thumbs-down': <Icons.ThumbsdownIcon />,
        'robot': <Icons.RobotIcon />,
        'hard-drive': <Icons.HarddriveIcon />,
        'paper-plane': <Icons.PaperplaneIcon />,
        'sliders': <Icons.SlidersIcon />,
        'info-circle': <Icons.InfocircleIcon />,
        'share-square-outline': <Icons.SharesquareoutlineIcon />
        // END_ICON_INSTANCES
      }),
      iconSize: figma.enum("Icon Size", {
        "Standalone - Small": "standalone---small",
        "Standalone - Medium": "standalone---medium",
        "Standalone - Large": "standalone---large",
        "Standalone - XL": "standalone---xl",
        "Standalone -2XL": "standalone--2xl",
        "Standalone - 3XL": "standalone---3xl",
        "Body - Small": "body---small",
        "Body - Default": "body---default",
        "Body - Large": "body---large",
        "Heading - H1": "heading---h1",
        "Heading - H2": "heading---h2",
        "Heading - H3": "heading---h3",
        "Heading - H4": "heading---h4",
        "Heading - H5": "heading---h5",
        "Heading - H6": "heading---h6",
        "Font size - XS": "font-size---xs",
        "Font size - Sm": "font-size---sm",
        "Font size - Med": "font-size---med",
        "Font size - Lg": "font-size---lg",
        "Font size - XL": "font-size---xl",
        "Font size - 2XL": "font-size---2xl",
        "Font size - 3xl": "font-size---3xl",
        "Font size - 4xl": "font-size---4xl",
      }),
    },
    example: (props) => <Icon {...props}>tesrte</Icon>,
  },
);