import React from 'react';
import { Modal } from 'src/components/Modal';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Modal,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2937-158',
  {
    props: {
      showComponentSlot: figma.boolean('Show component slot'),
      helpIcon: figma.boolean('Help icon'),
      customIcon: figma.boolean('Custom icon'),
      description: figma.boolean('Description'),
      type: figma.enum('Type', {
        Default: 'default',
        'No header': 'no-header'
      }),
      size: figma.enum('Size', {
        Small: 'small',
        Medium: 'medium',
        Large: 'large'
      })
    },
    example: (props) => <Modal />
  }
);

figma.connect(
  Modal,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=2940-18403',
  {
    props: {
      showComponentSlot: figma.boolean('Show component slot'),
      helpIcon: figma.boolean('Help icon'),
      description: figma.boolean('Description'),
      status: figma.enum('Status', {
        Success: 'success',
        Warning: 'warning',
        Danger: 'danger',
        Info: 'info',
        'Custom alert': 'custom-alert'
      }),
      size: figma.enum('Size', {
        Small: 'small',
        Medium: 'medium',
        Large: 'large'
      })
    },
    example: (props) => <Modal />
  }
);
