import React from 'react';
import { Progress } from 'src/components/Progress';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Progress,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=7644-38395',
  {
    props: {
      title: figma.string('Title'),
      showMainPercentage: figma.boolean('Show main percentage'),
      showOutsidePercentage: figma.boolean('Show outside percentage'),
      showMainIcon: figma.boolean('Show main icon'),
      showInsidePercentage: figma.boolean('Show inside percentage'),
      showHelperText: figma.boolean('Show helper text'),
      size: figma.enum('Size', {
        Default: 'default',
        Small: 'small',
        Large: 'large'
      }),
      state: figma.enum('State', {
        Default: 'default',
        Success: 'success',
        Warning: 'warning',
        Error: 'error'
      })
    },
    example: (props) => <Progress />
  }
);
