import React from 'react';
import { Wizard } from '../../src/components/Wizard/Wizard';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Wizard,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14628-18627',
  {
    props: {
      wizardStepTitle: figma.string('Wizard Step Title'),
      wizardStepContent: figma.string('Wizard Step Content'),
      type: figma.enum('Type', {
        'With Form': 'with-form',
        Empty: 'empty'
      }),
      withDrawer: figma.boolean('With drawer')
    },
    example: (_props) => <Wizard />
  }
);

figma.connect(
  Wizard,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14628-17329',
  {
    props: {
      description: figma.string('✏️ Description'),
      wizardTitle: figma.string('✏️Wizard Title')
    },
    example: (_props) => <Wizard />
  }
);

figma.connect(
  Wizard,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14628-23799',
  {
    props: {
      wizardDescription: figma.string('Wizard Description'),
      wizardStepTitle: figma.string('Wizard Step Title'),
      wizardStepContent: figma.string('Wizard Step Content'),
      type: figma.enum('Type', {
        'In Page Empty': 'in-page-empty',
        'With Drawer': 'with-drawer',
        'In Page': 'in-page'
      }),
      withDrawer: figma.boolean('With drawer')
    },
    example: (_props) => <Wizard />
  }
);

figma.connect(
  Wizard,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14628-17356',
  {
    props: {
      expandable: figma.boolean('Expandable'),
      navItem: figma.string('✏️ Nav item'),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        Disabled: 'disabled'
      }),
      expansion: figma.enum('Expansion', {
        'No expansion': 'no-expansion',
        'Expandable - Open': 'expandable---open',
        'Expandable - closed': 'expandable---closed'
      })
    },
    example: (_props) => <Wizard />
  }
);

figma.connect(
  Wizard,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14628-17334',
  {
    props: {
      wizardSubnavTitle: figma.string('✏️ Wizard Subnav title'),
      state: figma.enum('State', {
        Default: 'default',
        Hover: 'hover',
        Selected: 'selected',
        Disabled: 'disabled'
      })
    },
    example: (_props) => <Wizard />
  }
);

figma.connect(
  Wizard,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=14628-17431',
  {
    props: {},
    example: (props) => <Wizard />
  }
);
