import { DescriptionListGroup } from '@patternfly/react-core';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DescriptionListGroup,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1121-3571&m=dev',
  {
    props: {
      swapLabel: figma.instance('Swap label'),
      content: figma.string('✏️ Content'),
      type: figma.enum('Type', {
        Vertical: 'vertical',
        'Horizontal fluid': 'horizontal-fluid',
        'Horizontal fixed': 'horizontal-fixed'
      }),
      contentType: figma.enum('Content type', {
        Text: 'text',
        'Component swap': 'component-swap',
        'Icon + Text': 'icon---text'
      }),

      children: figma.children('*')
    },
    example: (props) => (
      <DescriptionListGroup swapLabel={props.swapLabel} content={props.content} type={props.type} contentType={props.contentType}>
        {props.children}
      </DescriptionListGroup>
    )
  }
);
