import { DescriptionList } from '@patternfly/react-core';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  DescriptionList,
  'https://www.figma.com/design/aEBBvq0J3EPXxHvv6WgDx9/PatternFly-6--Components-Test?node-id=1121-3946&m=dev',
  {
    props: {
      spacing: figma.enum('Spacing', {
        Default: 'default',
        Compact: 'compact'
      }),
      orientation: figma.enum('Orientation', {
        Vertical: 'vertical',
        'Horizontal - Fixed': 'horizontal---fixed',
        'Horizontal - Fluid': 'horizontal---fluid'
      }),

      children: figma.children('*')
    },
    example: (props) => <DescriptionList spacing={props.spacing} orientation={props.orientation}></DescriptionList>
  }
);
