import React from 'react';
import { SimpleList } from './SimpleList';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  SimpleList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=4410-20691',
  {
    props: {
      type: figma.enum('Type', {
        Default: 'default',
        Grouped: 'grouped'
      })
    },
    example: (props) => <SimpleList />
  }
);

figma.connect(
  SimpleList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=4410-20689',
  {
    props: {
      text: figma.string('Text')
    },
    example: (props) => <SimpleList />
  }
);

figma.connect(
  SimpleList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=4410-20708',
  {
    props: {},
    example: (props) => <SimpleList />
  }
);

figma.connect(
  SimpleList,
  'https://www.figma.com/design/VMEX8Xg2nzhBX8rfBx53jp/branch/H3LonYnwH26v9zNEa2SXFk/PatternFly-6%3A-Components?m=auto&node-id=4410-20664',
  {
    props: {
      text: figma.string('Text'),
      state: figma.enum('State', {
        Default: 'default',
        'Hover - Light': 'hover---light',
        'Hover - Dark': 'hover---dark',
        'Selected - Light': 'selected---light',
        'Selected - Dark': 'selected---dark',
        Disabled: 'disabled'
      }),
      type: figma.enum('Type', {
        Default: 'default',
        Link: 'link'
      })
    },
    example: (props) => <SimpleList />
  }
);
