name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    types: ['opened', 'edited']

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step prints an output (time) from the previous step's action.
      - name: Echo the PR text changes
        run: echo '${{ github.event.changes }}'
      # This step prints an output (time) from the previous step's action.
      - name: Echo the PR text
        run: echo '${{ github.event.pull_request }}'