name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
  pull_request:
    types: ['opened', 'edited']

jobs:
  build:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Echo the PR title
        run: echo '${{ github.event.pull_request.title }}'
      - name: Echo the PR text
        run: echo '${{ github.event.pull_request.body }}'