name: Close stale issues and PRs
on:
  schedule:
    - cron: 37 11 * * *
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 14
          exempt-issue-labels: accessibility,breaking change :boom:,security,pinned
          stale-issue-label: wontfix
          stale-issue-message: This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
          stale-pr-message: This PR has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
          close-issue-message: 'This issue has been closed because it has not had activity since being marked as stale.'
          close-pr-message: 'This PR has been closed because it has not had activity since being marked as stale.'
