name: release
on:
  push:
    branches:
      - main
jobs:
  %build%
  %lint%
  %test_jest%
  %docs%
  %demo_app%
  %test_integration%
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test_jest, docs, test_integration]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN_REDALLEN }} # needs to be an admin token to get around branch protection
      GH_PR_TOKEN: ${{ secrets.GH_PR_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN_REDALLEN }} # needs to be an admin token to get around branch protection
          fetch-depth: "0"
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      %install%
      %dist%
      - name: Deploy to NPM and Github
        run: .github/release.sh

